Custom spdlog sink for logging to stdout/stderr from a single sink
CARTAvis/carta-backend pull request #1005
Opened 2022-01-17 14:42 UTC by jolopezl

Closes #869.

To get a _rerouting_ to stdout/stderr depending on the message level a custom sink for `spdlog` is introduced. While this is quite direct for a simple sink, it requires some code duplication if fancy colors are wanted, but I think it's ok.

To test it, I added within the main function the following messages after the logger initialization:
```
        spdlog::info("this should appear in stdout");
        spdlog::warn("this should appear in stdout");
        spdlog::error("this should appear in stderr");
        spdlog::critical("this should appear in stderr");
```
Then, I get:
```
$ ./carta_backend > logging.out 2> logging.err
^C$ cat logging.out 
[2022-01-17 15:37:38.224] [CARTA] [info] Writing to the log file: /Users/lopez/.carta/log/carta.log
[2022-01-17 15:37:38.224] [CARTA] [debug] Reading user settings from /Users/lopez/.carta/backend.json.
[2022-01-17 15:37:38.224] [CARTA] [info] this should appear in stdout
[2022-01-17 15:37:38.224] [CARTA] [warning] this should appear in stdout
[2022-01-17 15:37:38.227] [CARTA] [info] /Users/lopez/temp/CARTAvis/carta-backend/build/./carta_backend: Version 3.0.0-beta.2c
[2022-01-17 15:37:38.230] [CARTA] [info] CARTA gRPC service available at 0.0.0.0:50071
[2022-01-17 15:37:38.230] [CARTA] [info] CARTA gRPC token: EE7CC612-A49E-4278-A34E-AFB8B9AA472B
[2022-01-17 15:37:38.232] [CARTA] [info] Serving CARTA frontend from /Users/lopez/temp/CARTAvis/carta-frontend/build
[2022-01-17 15:37:38.232] [CARTA] [info] Listening on port 3020 with top level folder /, starting folder /Users/lopez/temp/CARTAvis/data, and 4 OpenMP worker threads
[2022-01-17 15:37:38.232] [CARTA] [info] CARTA is accessible at http://localhost:3020/?token=EDB898F1-FF87-44F3-A6EA-3E625E5E1D93
[2022-01-17 15:37:39.823] [CARTA] [info] Exiting backend.
$ cat logging.err 
[2022-01-17 15:37:38.224] [CARTA] [error] this should appear in stderr
[2022-01-17 15:37:38.227] [CARTA] [critical] this should appear in stderr
```

The only thing that puzzles me right now is that the `STDOUT_TAG`, now renames `CARTA_LOGGER_TAG` wasn't printed before. I am not sure if that was ok. Now you can see that the log messages come from `CARTA`. I think this is ok to notice the separation between CARTA and CASA logging messages clearly.

![carta_backend_log](https://user-images.githubusercontent.com/3409812/149789605-98416502-59a5-4454-8b66-d7f4ffc943d5.png)

2022-01-19 01:53 UTC, markccchiang approved these changes

2022-01-20 10:30 UTC, confluence requested changes

2022-01-20 10:30 UTC, confluence commented on src/Logger/Logger.cc
> +    stdout_console_sink->set_pattern(CARTA_LOGGER_PATTERN);
This variable should probably be renamed to `console_sink`.

2022-01-20 11:20 UTC, confluence approved these changes

2022-01-20 11:28 UTC, veggiesaurus approved these changes

2022-01-20 11:28 UTC, merged