1058 Fix CoordinateSystem mem leaks
CARTAvis/carta-backend pull request #1062
Opened 2022-03-16 20:27 UTC by pford

Closes #1058 

Frame returned casacore::CoordinateSystem clone which needed to be deleted by recipient.  Now all requests return a std::shared_ptr to the coordinate system.

Also refactor FileLoader:

- Use FileLoader IPos instead of casacore::IPosition for consistency. 
- GetShape and GetCoordinateSystem to return requested object instead of bool.

2022-03-23 12:44 UTC, veggiesaurus commented
@pford I'm still getting the `RegionHandler` error. I've attached the valgrind output, if that's any help.
![image](https://user-images.githubusercontent.com/592504/159701942-e72580cc-86a2-4488-8ab3-3dca5085c0f9.png)


[valgrind.zip](https://github.com/CARTAvis/carta-backend/files/8332942/valgrind.zip)

2022-03-23 13:48 UTC, confluence requested changes

2022-03-23 13:48 UTC, confluence commented on src/ImageData/FileLoader.cc
> +casacore::IPosition FileLoader::GetShape() {
Should this be `IPos`, if we're trying to use that consistently? There are also a few other places where we're still using `casacore::IPosition`.

2022-03-23 13:48 UTC, confluence commented on src/ImageData/FileLoader.cc
> +casacore::IPosition FileLoader::GetShape() {
I'm not 100% sure if it makes sense to keep using `IPos`, when we don't use aliases for other casacore types. I would also be happy to remove these completely and use the full type name everywhere.

2022-03-26 03:36 UTC, confluence approved these changes

2022-03-28 16:10 UTC, pford commented
Updated title and description to include #1059

2022-03-29 07:45 UTC, confluence commented
Still approved after #1059 fix.

2022-03-29 09:10 UTC, veggiesaurus commented
Just running `valgrind` once more to double check, then I'll approve :slightly_smiling_face:

2022-03-29 09:15 UTC, veggiesaurus approved these changes

2022-03-29 09:15 UTC, merged