Add moment map generation information to FITS header
CARTAvis/carta-backend pull request #1091
Opened 2022-04-28 05:29 UTC by markccchiang

Closes #1024. Adding some information to the FITS header history about moment map generation. As shown below:
<img width="812" alt="截圖 2022-04-28 下午1 22 13" src="https://user-images.githubusercontent.com/5379602/165682618-b70b2f34-d485-4021-9711-4ae2597ef0c2.png">

2022-05-02 05:04 UTC, kswang1029 commented
@markccchiang quick questions, does this new info exist in the header of the in-memory moment images (the image auto appended to carta after the moment image is generated)? I am not sure where I can locate this new info. 🤔

I suggest we refine the extra moment generation info as the following:
1. add a string like CARTA MOMENT GENERATOR LOG before add extra info from CARTA
2. the extra info should include
a. the input image for moment map generation
b. region info (pixel coordinate should be fine)
c. spectral range (channel, freq, and velocity). This is included already. 👍 
d. mask info

2022-05-03 05:01 UTC, markccchiang commented
@kswang1029 as for the moment region info about pixel coordinates. Does it mean the control points of regions (e.g., point, rectangle, polygon..)?

2022-05-03 05:06 UTC, kswang1029 commented
> @kswang1029 as for the moment region info about pixel coordinates. Does it mean the control points of regions (e.g., point, rectangle, polygon..)?

yes.

2022-05-03 06:12 UTC, markccchiang commented
Now the new moment map generation info from the header of moment images would look like this:

<img width="796" alt="截圖 2022-05-03 下午1 55 45" src="https://user-images.githubusercontent.com/5379602/166411160-ceaa42ba-2fbe-46d0-9f71-97db9328d94d.png">

2022-05-03 06:27 UTC, kswang1029 commented
> Now the new moment map generation info from the header of moment images would look like this:
> 
> <img alt="截圖 2022-05-03 下午1 55 45" width="796" src="https://user-images.githubusercontent.com/5379602/166411160-ceaa42ba-2fbe-46d0-9f71-97db9328d94d.png">

this works nicely! Could you add region type too? Also we need rotation angle be part of the info.  

> HISTORY =  / Region control points: [402.9424, 374.0267], [242.3408, 294.6644] 

I suggest the format like this (please refer to the header of the exported tsv file from the spectral profiler)

rotbox[[402.942341pix, 374.026678pix], [242.340792pix, 294.664372pix], 0.000000deg]

2022-05-04 03:14 UTC, kswang1029 approved these changes
👍

2022-05-05 14:02 UTC, kswang1029 commented
@markccchiang just realized that the polarization info is missing. Could you add it too?

2022-05-06 02:43 UTC, kswang1029 requested changes
thanks for adding polarization info. It works with usual Stokes. Now CARTA supports computed polarization quantities too such as polarized intensity, angle, etc, so when these are selected, the displayed text is unknown.

HISTORY =  / Stokes: Unknown 

I suggest we call show this as 

Polarization: Stokes Q
Polarization: Fractional polarized intensity
Polarization: XY

2022-05-06 16:13 UTC, markccchiang commented
> I suggest we call show this as
> 
> Polarization: Stokes Q 
> Polarization: Fractional polarized intensity 
> Polarization: XY

Please confirm are the full name of the computed stokes correct?

Ptotal: Total linearly polarized intensity
Plinear: Linearly polarized intensity
PFtotal: Total fractional linear polarization
PFlinear: Fractional linear polarization
Pangle: Linearly polarized angle

2022-05-06 20:09 UTC, kswang1029 commented
@markccchiang please consider

Ptotal: total polarization intensity
Plinear: linear polarization intensity
PFtotal: fractional total polarization intensity
PFlinear: fractional linear polarization intensity
Pangle: polarization angle

2022-05-07 08:03 UTC, kswang1029 approved these changes
looking good! 👍

2022-05-09 08:55 UTC, confluence commented on src/Frame/Frame.cc
> +        }
Could this be changed to a map lookup?

2022-05-09 17:26 UTC, confluence approved these changes

2022-05-09 17:29 UTC, merged