Fix changelog before release
CARTAvis/carta-backend pull request #1099
Opened 2022-05-05 18:18 UTC by confluence

I have added what I think are all the relevant entries that were missing from the changelog. I have also moved an entry that I incorrectly added to the previous release, and changed the title of the current release section to `Unreleased` -- this should only be changed to the release version during the release.

I have omitted changes which affect only unit tests, compilation or our CI, since I don't think these are user-facing, but I did add a catch-all entry for all the ASAN fixes and memory leak fixes.

2022-05-05 19:05 UTC, pford commented
Should the DS9 import bug be added, or is it internal only (ASAN)?  If so, it was missed.

* Fixed DS9 import bug on MacOS ([#1066](https://github.com/CARTAvis/carta-backend/issues/1066)), ([#1096](https://github.com/CARTAvis/carta-backend/issues/1096)).

2022-05-05 19:16 UTC, pford approved these changes
All my stuff is in.  Thanks @confluence !

2022-05-05 19:24 UTC, jolopezl requested changes
Thanks! I am sorry for not adding this when due. I am missing the performance improvements in the image cache (#967, #1034).

2022-05-05 19:26 UTC, confluence commented
> I am missing the performance improvements in the image cache (#967, #1034).

I was on the fence about that, but you're right; if it's a performance optimisation, that's user-facing. I'll put it in.

2022-05-05 19:27 UTC, jolopezl commented
> > I am missing the performance improvements in the image cache (#967, #1034).
> 
> I was on the fence about that, but you're right; if it's a performance optimisation, that's user-facing. I'll put it in.

Thanks!

2022-05-06 03:27 UTC, kswang1029 commented on CHANGELOG.md
>  * Added computed stokes images and supported the analysis (profiles, contours, statistics, etc.) of them ([#433](https://github.com/CARTAvis/carta-backend/issues/433)).
stokes -> Stokes

2022-05-06 15:18 UTC, jolopezl approved these changes

2022-05-09 09:11 UTC, merged