Modify the compressed FITS image loader destruction
CARTAvis/carta-backend pull request #1119
Opened 2022-06-03 16:20 UTC by markccchiang

I think it can solve #999 and #1014. When doing statistics calculations, several copies of an image loader are created and run in parallel. These copies are deleted when calculations are done. In CartaFitsImage, the close file action can only be executed when all of the CartaFitsImage objects are destroyed.

2022-06-06 04:13 UTC, kswang1029 commented
@markccchiang confirmed this PR does not result in any regressions that the current e2e tests are capable to capture. Manual tests are on the way before approving the PR.

2022-06-06 06:36 UTC, kswang1029 approved these changes
tested manually with compressed fits and confirmed that region statistics, line/polyline spatial profiler, region histogram, pv generator and region spectral profile work and do not trigger crash.

2022-06-14 23:27 UTC, pford commented
Keeping track of copies sounds like a shared_ptr workaround.  But the real issue is several CartaFitsImages sharing a single fitsfile* pointer.  Maybe instead the copy should have a null _fptr and it will open the file when it needs to read something?

2022-06-14 23:32 UTC, pford requested changes

2022-06-14 23:32 UTC, pford commented on src/ImageData/CartaFitsImage.cc
> +      _is_copy(true) {
Set _fptr(nullptr) instead?

2022-06-15 06:29 UTC, pford commented
It occurred to me that opening the same gz file in another CartaFitsImage may decompress it into memory again.  Can you test this?  Your solution was probably better.

2022-06-15 07:04 UTC, markccchiang commented
> It occurred to me that opening the same gz file in another CartaFitsImage may decompress it into memory again. Can you test this? Your solution was probably better.

A quick test with `psrecord`. The memory usage for statistics calculations with multiple `_fptr` is 

![test3](https://user-images.githubusercontent.com/5379602/173762915-12edbca4-960b-4ac8-9c2b-309d33498dc2.png)

On the other hand, the memory usage for statistics calculations with a single `_fptr` is 

![test2](https://user-images.githubusercontent.com/5379602/173763105-f7d4fa59-b105-45c3-b6eb-83c7442ac7cf.png)

So maybe it is better to use the original method?

2022-06-15 07:04 UTC, markccchiang commented
> It occurred to me that opening the same gz file in another CartaFitsImage may decompress it into memory again. Can you test this? Your solution was probably better.

A quick test with `psrecord`. The memory usage for statistics calculations with multiple `_fptr` is 

![test3](https://user-images.githubusercontent.com/5379602/173762915-12edbca4-960b-4ac8-9c2b-309d33498dc2.png)

On the other hand, the memory usage for statistics calculations with a single `_fptr` is 

![test2](https://user-images.githubusercontent.com/5379602/173763105-f7d4fa59-b105-45c3-b6eb-83c7442ac7cf.png)

So maybe it is better to use the original method?

2022-06-15 14:43 UTC, pford commented
Yes, please put it back to the tested version.  Sorry about that, I forgot about decompression!

2022-06-15 15:51 UTC, pford approved these changes

2022-06-15 15:52 UTC, merged