Angus/remove splatalogue
CARTAvis/carta-backend pull request #1120
Opened 2022-06-06 09:52 UTC by veggiesaurus

Removes all splatalogue functionality from the backend, and also removes use of `curl_easy_escape`. This means we can remove curl as a dependency.

2022-06-06 10:44 UTC, confluence reviewed
This looks fine. Is there also a protobuf PR to remove these messages?

2022-06-06 10:44 UTC, confluence commented on CHANGELOG.md
> +* Removed Splatalogue interfaction from backend codebase and removed dependency onn libcurl ([#994](https://github.com/cartavis/carta-backend/issues/994)).
Typo? Interface or interaction?

2022-06-06 10:45 UTC, confluence approved these changes

2022-06-06 10:45 UTC, confluence requested changes
Forgot the typo.

2022-06-06 13:52 UTC, veggiesaurus commented on CHANGELOG.md
> +* Removed Splatalogue interfaction from backend codebase and removed dependency onn libcurl ([#994](https://github.com/cartavis/carta-backend/issues/994)).
fixed :)

2022-06-06 13:53 UTC, confluence approved these changes

2022-06-06 13:54 UTC, veggiesaurus commented
> This looks fine. Is there also a protobuf PR to remove these messages?

I can't remember how we handled things before. Do we simply just remove the messages and the entries from the enum?

2022-06-06 14:46 UTC, acdo2002 commented
There are two protobuf related to splatalogue
[73, CARTA.SplataloguePing],
[74, CARTA.SplataloguePong]
There is no ICD tests for these two protobuf.

I have a question, would this PR(remove splatalogue) affect [67, CARTA.SpectralLineRequest] and [68, CARTA.SpectralLineResponse] protobuf? Because we have the ICD tests for these two protobuf.

2022-06-06 14:49 UTC, kswang1029 commented
> There are two protobuf related to splatalogue [73, CARTA.SplataloguePing], [74, CARTA.SplataloguePong] There is no ICD tests for these two protobuf.
> 
> I have a question, would this PR(remove splatalogue) affect [67, CARTA.SpectralLineRequest] and [68, CARTA.SpectralLineResponse] protobuf? Because we have the ICD tests for these two protobuf.

We can remove all splatalogue related ICD tests after this PR is merged.

2022-06-06 14:55 UTC, acdo2002 commented
> > There are two protobuf related to splatalogue [73, CARTA.SplataloguePing], [74, CARTA.SplataloguePong] There is no ICD tests for these two protobuf.
> > I have a question, would this PR(remove splatalogue) affect [67, CARTA.SpectralLineRequest] and [68, CARTA.SpectralLineResponse] protobuf? Because we have the ICD tests for these two protobuf.
> 
> We can remove all splatalogue related ICD tests after this PR is merged.

Ok! Then we only need to remove three ICD tests:
SPECTRAL_LINE_QUERY.test.ts
SPECTRAL_LINE_QUERY_INTENSITY_LIMIT.test.ts
SPECTRAL_LINE_QUERY_WIDE_FREQ.test.ts

2022-06-07 04:15 UTC, kswang1029 commented
@veggiesaurus @confluence no regression is observed via the current set of e2e tests.

2022-06-07 06:46 UTC, confluence commented
> I can't remember how we handled things before. Do we simply just remove the messages and the entries from the enum?

Yes, from the history it looks like that's what we do now.

2022-06-14 08:00 UTC, ajm-asiaa approved these changes
This looks good.

I tried the spectral line query and I feel it is a lot faster now than when it was done by the backend.

2022-06-14 08:37 UTC, merged