Recognize the FITS gzip file from ALMA archive
CARTAvis/carta-backend pull request #1131
Opened 2022-06-17 01:56 UTC by markccchiang

Closes #1130. It seems the magic number of fits.gz from ALMA archive is different from that of ordinary FITS gzip files. Although they are the same file type. @kswang1029 could you please check does it can also recognize the other fits.gz files from ALMA archive? Thank you!

2022-06-17 02:00 UTC, kswang1029 commented
uh, nice catch. Does this imply with different brands of gzip, the magic number is different?

2022-06-17 06:41 UTC, markccchiang commented
> uh, nice catch. Does this imply with different brands of gzip, the magic number is different?

According to [this link](https://docs.fileformat.com/compression/gz/), the magic number of gz file is `1f 8b`. The other number corresponds to the compression method (usually `08` for DEFLATE) and file flags. The header of the ordinary gz file is `1f8b 0808` and the header of ALMA is `1f8b 0800`. I guess the only difference between them is the file flag. So maybe we can identify gz files by only checking whether it has `1f8b` number.

2022-06-20 05:10 UTC, kswang1029 approved these changes
checked with alma gz images and some others in the test image pool. All working. No regression is observed from e2e tests.

2022-06-20 14:53 UTC, confluence requested changes
Other than the function name, I think this is fine.

2022-06-20 14:53 UTC, confluence commented on src/Util/File.cc
> +bool IsGzFile(uint32_t magic_number) {
This is a confusing name for a function which takes a magic number as a parameter (not a file name or file object). I would suggest `IsGzMagicNumber` for more clarity.

2022-06-20 15:41 UTC, confluence approved these changes

2022-06-20 15:42 UTC, merged