#1129 Fix DS9 region imports with region properties
CARTAvis/carta-backend pull request #1135
Opened 2022-06-22 20:12 UTC by pford

Closes #1129 

Fix parsing of DS9 region properties with two arguments: `line=0 0` indicating arrow heads and "point=circle 5' indicating the point shape and size (bug mentioned in #1064).  These properties are not currently supported in CARTA but the file is parsed successfully and the regions are imported.

2022-06-23 03:00 UTC, kswang1029 requested changes
Spotted a crash issue with ds9 region file.
from ds9

> Point
> 
> Point regions have an associated type and size. Use the point property to set the point type.
> 
> Example: point(100,100) # point=diamond 31

With the attached region file (using the same test image as attached in #1129 , the backend will crash when loading the region.
[point_diamond.reg.zip](https://github.com/CARTAvis/carta-backend/files/8963301/point_diamond.reg.zip)

2022-06-23 03:05 UTC, kswang1029 commented
I will try to create a ds9 region file including all possible ds9 regions for testing purpose.

2022-06-23 14:15 UTC, pford commented
> Spotted a crash issue with ds9 region file. from ds9
> 
> > Point
> > Point regions have an associated type and size. Use the point property to set the point type.
> > Example: point(100,100) # point=diamond 31
> 
> With the attached region file (using the same test image as attached in #1129), the backend will crash when loading the region. [point_diamond.reg.zip](https://github.com/CARTAvis/carta-backend/files/8963301/point_diamond.reg.zip)

This works in my dev build with the `point=diamond 10` line

2022-06-23 14:53 UTC, kswang1029 commented
> > Spotted a crash issue with ds9 region file. from ds9
> > > Point
> > > Point regions have an associated type and size. Use the point property to set the point type.
> > > Example: point(100,100) # point=diamond 31
> > 
> > 
> > With the attached region file (using the same test image as attached in #1129), the backend will crash when loading the region. [point_diamond.reg.zip](https://github.com/CARTAvis/carta-backend/files/8963301/point_diamond.reg.zip)
> 
> This works in my dev build with the `point=diamond 10` line

you are right. Not sure what I saw/did this morning. 🤔

2022-06-23 14:53 UTC, kswang1029 approved these changes

2022-06-24 03:54 UTC, kswang1029 commented
@pford I think I know why I could crash the backend by load a point region from a region file.

could you try the following cases please?
1. `point(269.0875791,-21.9581835) # point=circle 10` this should work
2. `point(269.0875791,-21.9581835) # point=circle` this would crash the backend in my case

2022-06-24 04:13 UTC, kswang1029 commented
> I will try to create a ds9 region file including all possible ds9 regions for testing purpose.

If I manually patch the `# point=circle` issue, all regions generated with ds9 as a region file can be loaded in CARTA successfully. Non-implemented ds9 regions are ignored.

ds9
![all_region_generated_with_ds9](https://user-images.githubusercontent.com/20819712/175460758-6c0fadac-62c6-45db-9a2a-72d6c9be1194.png)

loaded in carta
![Screen Shot 2022-06-24 at 12 11 41](https://user-images.githubusercontent.com/20819712/175460822-6df17ddc-bc9f-46d6-ac2c-10d94395db9a.png)


to conclude, carta is fine loading ds9 regions as far as I can see. 👍

2022-06-24 11:58 UTC, confluence approved these changes

2022-06-24 11:58 UTC, confluence commented
@kswang1029 Does this mean that you are re-approving this, or do you still need to check something?

2022-06-24 12:19 UTC, kswang1029 commented
> @kswang1029 Does this mean that you are re-approving this, or do you still need to check something?

There seems to be crash bug to be fixed still.

2022-06-24 16:37 UTC, pford commented
@kswang1029 thanks for catching this, it used to work until I broke it.  Please test again.

2022-06-28 00:28 UTC, kswang1029 approved these changes
this works properly now. 👍

2022-06-28 07:23 UTC, merged