PV generator features
CARTAvis/carta-backend pull request #1195
Opened 2022-09-14 15:59 UTC by pford

Enhancements to the PV generator

* What is implemented or fixed? Mention the linked issue(s), if any.
Implements #1175 , #1176 , and #1177 .

* How does this PR solve the issue? Give a brief summary.
For reversed axes, the profiles are added as columns instead of rows and the coordinate system coordinates are reversed.  To keep a PV image, an index is incremented and added as a suffix to the new PV image name, as well as used to create a new file_id.  For the spectral range, only the channels requested are used for the spectral profiles.

* Are there any companion PRs (frontend, protobuf)?
Frontend PR [#2007](https://github.com/CARTAvis/carta-frontend/pull/2007), protobuf PR [#75](https://github.com/CARTAvis/carta-protobuf/pull/75)

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
Frontend PV generator now shows the spectral range and reversed-axes options.  After clicking "Generate", a popup asks whether to overwrite a previous image.

**Checklist**

- [ ] changelog updated
- [ ] e2e test passing / added corresponding fix
- [ ] protobuf updated to add PvRequest fields
- [ ] added reviewers and assignee
- [ ] added ZenHub estimate, milestone, and release
- [ ] added backend unit tests

2022-09-19 05:59 UTC, kswang1029 requested changes
@pford could you check if the header entries defining the FREQ axis is correctly set if we apply a spectral range for the pv generation? In the following example, the middle pv image is with 0~100 km/s and the right pv image is with 100~200 km/s but from the pv images we see the velocity range is about 320~420 in _both_ cases. I checked the header of those pv images and the spectral axis definition is identical which should not be the case. 

<img width="1012" alt="Screen Shot 2022-09-19 at 13 56 13" src="https://user-images.githubusercontent.com/20819712/190957325-b089244d-d99d-44b6-aa1d-9ab0a082540a.png">

2022-09-19 20:34 UTC, pford commented
@kswang1029 I made a change to set the reference value of the spectral coordinate to the frequency of the first channel in the range; the reference pixel is 0.  Please retest.

2022-09-20 02:24 UTC, kswang1029 commented
@pford I noticed a backend crash in this branch (not in dev):
1. load a cube
2. make a point region
3. enable spectral profiler to see a point region profile
4. drag-and-drop the point region to elsewhere in the image and we will see the backend crash.

> libc++abi: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found

Thread 3 Crashed:
0   libsystem_kernel.dylib        	    0x7ff814fea00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8150201ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff814f6bd24 abort + 123
3   libc++abi.dylib               	    0x7ff814fdc082 abort_message + 241
4   libc++abi.dylib               	    0x7ff814fcd1a5 demangling_terminate_handler() + 242
5   libobjc.A.dylib               	    0x7ff814ec9e19 _objc_terminate() + 104
6   libc++abi.dylib               	    0x7ff814fdb4a7 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	    0x7ff814fddd05 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	    0x7ff814fddccc __cxa_throw + 116
9   carta_backend                 	       0x108cc1fb8 std::__1::__throw_out_of_range(char const*) + 56 (stdexcept:267)
10  carta_backend                 	       0x108cd1a2f std::__1::unordered_map<int, std::__1::shared_ptr<carta::Frame>, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, std::__1::shared_ptr<carta::Frame> > > >::at(int const&) + 12 (unordered_map:1792) [inlined]
11  carta_backend                 	       0x108cd1a2f carta::RegionHandler::FillSpectralProfileData(std::__1::function<void (CARTA::SpectralProfileData)>, int, int, bool) + 2271 (RegionHandler.cc:1300)
12  carta_backend                 	       0x108d03257 carta::Session::SendSpectralProfileData(int, int, bool) + 135 (Session.cc:1593)
13  carta_backend                 	       0x108d10bfc carta::Session::UpdateRegionData(int, int, bool, bool) + 22 [inlined]
14  carta_backend                 	       0x108d10bfc carta::Session::RegionDataStreams(int, int) + 44 (Session.cc:1797)
15  carta_backend                 	       0x108cf0a66 carta::RegionDataStreamsTask::execute() + 22 (OnMessageTask.cc:65)
16  carta_backend                 	       0x108d544f1 carta::ThreadManager::StartEventHandlingThreads(int)::$_0::operator()() const + 114 (ThreadingManager.cc:54) [inlined]
17  carta_backend                 	       0x108d544f1 decltype(static_cast<carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(fp)()) std::__1::__invoke<carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(carta::ThreadManager::StartEventHandlingThreads(int)::$_0&&) + 114 (type_traits:3918) [inlined]
18  carta_backend                 	       0x108d544f1 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0>&, std::__1::__tuple_indices<>) + 114 (thread:287) [inlined]
19  carta_backend                 	       0x108d544f1 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0> >(void*) + 177 (thread:298)
20  libsystem_pthread.dylib       	    0x7ff8150204e1 _pthread_start + 125
21  libsystem_pthread.dylib       	    0x7ff81501bf6b thread_start + 15

2022-09-21 05:00 UTC, kswang1029 commented
@pford please refer to the test image I send to you vis slack. The velocity axis of the pv image is not consistent with the velocity axis of the spectral profile.

<img width="1691" alt="Screen Shot 2022-09-21 at 12 57 23" src="https://user-images.githubusercontent.com/20819712/191417988-b13a6189-c61c-4f1b-a80a-e8577623f6df.png">

2022-09-27 21:45 UTC, pford commented
I fixed both issues: the PV image spectral axis and the spectral profile crash when a region changes.

2022-09-28 01:31 UTC, kswang1029 commented
> I fixed both issues: the PV image spectral axis when spectral range is set, and the spectral profile crash when a region changes.

nice 👍 this is ready for code review.

2022-09-28 02:31 UTC, kswang1029 commented
no regression is observed from the current e2e tests. Due to UI changes, I have created a fix branch and it will be merged after the pair of PV improvements is merged.

After some code review, I will re-run e2e tests.

2022-09-28 15:22 UTC, pford commented
@confluence the HDF5 spectral profiles for a PV image are for temporary box regions along the line, and the temporary region id is reused for each.  So it did not make sense to cache the profiles, therefore did not need to worry about the spectral range in the cache.

2022-09-28 23:00 UTC, pford commented
Having just worked on the moment image file ids with the "keep" option, I changed the PV file_id to a negative number to ensure there is no duplication.  This should not affect the testing already done.

2022-09-29 09:07 UTC, confluence approved these changes

2022-10-03 06:23 UTC, markccchiang approved these changes

2022-10-06 15:23 UTC, pford commented
@kswang1029 this PR has been code reviewed.  All that remains is the final e2d tests and your approval.

2022-10-06 23:06 UTC, kswang1029 commented
> @kswang1029 this PR has been code reviewed. All that remains is the final e2d tests and your approval.

Apologies. I should put a note that I am waiting for the frontend PR in order to have a final test before approving.

2022-10-11 13:34 UTC, kswang1029 commented
@pford I found another backend crashing issue:

A likely way to reproduce the issue:
1. define a channel range for making a pv image
2. then make a new pv image with pv axes swapped and keep the 1st pv image
3. now we see two pv images in the viewer
4. then make another new pv image with pv axes swapped again but do not keep all the previous pv image
5. when this new pv image is generating, the backend would crash.

If you need the exact test image please let me know (it is 50 MB ish)

https://user-images.githubusercontent.com/20819712/195104660-383f0128-1c94-4ddb-a945-78f62001f91e.mov





The terminal log shows:

> libc++abi: terminating with uncaught exception of type casacore::TableError: Error (Bad file descriptor) when releasing lock on ??v_
> Abort trap: 6


The macOS console shows

> Thread 3 Crashed:
> 0   libsystem_kernel.dylib        	    0x7ff81864800e __pthread_kill + 10
> 1   libsystem_pthread.dylib       	    0x7ff81867e1ff pthread_kill + 263
> 2   libsystem_c.dylib             	    0x7ff8185c9d24 abort + 123
> 3   libc++abi.dylib               	    0x7ff81863a082 abort_message + 241
> 4   libc++abi.dylib               	    0x7ff81862b1a5 demangling_terminate_handler() + 242
> 5   libobjc.A.dylib               	    0x7ff818527e19 _objc_terminate() + 104
> 6   libc++abi.dylib               	    0x7ff8186394a7 std::__terminate(void (*)()) + 8
> 7   libc++abi.dylib               	    0x7ff818639458 std::terminate() + 56
> 8   libcasa_images.6.dylib        	       0x10cf010ce casacore::PagedImage<float>::~PagedImage() + 14
> 9   libcasa_images.6.dylib        	       0x10cf1b219 casacore::SubImage<float>::~SubImage() + 41
> 10  carta_backend                 	       0x10ad5c29f carta::FileLoader::GetSubImage(carta::StokesRegion const&, casacore::SubImage<float>&) + 143 (FileLoader.cc:427)
> 11  carta_backend                 	       0x10acd7026 carta::Frame::GetRegionData(carta::StokesRegion const&, std::__1::vector<float, std::__1::allocator<float> >&) + 86 (Frame.cc:1612)
> 12  carta_backend                 	       0x10aea7fb7 carta::RegionHandler::GetTemporaryRegionProfile(int, int, carta::RegionState&, std::__1::shared_ptr<casacore::CoordinateSystem>, bool, AxisRange const&, int, double&) + 1351 (RegionHandler.cc:2750)
> 13  carta_backend                 	       0x10aea4407 carta::RegionHandler::GetFixedPixelRegionProfiles(int, int, int, bool, AxisRange const&, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, carta::RegionState&, std::__1::shared_ptr<casacore::CoordinateSystem>, std::__1::function<void (float)>&, casacore::Matrix<float, std::__1::allocator<float> >&, double&, bool&, bool) + 5639 (RegionHandler.cc:2092)
> 14  carta_backend                 	       0x10ae955cd carta::RegionHandler::GetLineProfiles(int, int, int, AxisRange const&, bool, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (float)>&, double&, casacore::Matrix<float, std::__1::allocator<float> >&, bool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool) + 813 (RegionHandler.cc:1949)
> 15  carta_backend                 	       0x10aea17d1 carta::RegionHandler::GetLineSpatialData(int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, std::__1::function<void (std::__1::vector<float, std::__1::allocator<float> >, double)> const&) + 497 (RegionHandler.cc:1837)
> 16  carta_backend                 	       0x10aea141c carta::RegionHandler::FillLineSpatialProfileData(int, int, std::__1::function<void (CARTA::SpatialProfileData)>) + 1868 (RegionHandler.cc:1810)
> 17  carta_backend                 	       0x10aecb0fd carta::Session::SendSpatialProfileData(int, int) + 861 (Session.cc:1543)
> 18  carta_backend                 	       0x10aecf32e carta::Session::OnSetSpatialRequirements(CARTA::SetSpatialRequirements const&) + 1070 (Session.cc:926)
> 19  carta_backend                 	       0x10aeea5b4 carta::GeneralMessageTask<CARTA::SetSpatialRequirements>::execute() + 20 (OnMessageTask.tcc:22)
> 20  carta_backend                 	       0x10af1cb31 carta::ThreadManager::StartEventHandlingThreads(int)::$_0::operator()() const + 114 (ThreadingManager.cc:54) [inlined]
> 21  carta_backend                 	       0x10af1cb31 decltype(static_cast<carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(fp)()) std::__1::__invoke<carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(carta::ThreadManager::StartEventHandlingThreads(int)::$_0&&) + 114 (type_traits:3918) [inlined]
> 22  carta_backend                 	       0x10af1cb31 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0>&, std::__1::__tuple_indices<>) + 114 (thread:287) [inlined]
> 23  carta_backend                 	       0x10af1cb31 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, carta::ThreadManager::StartEventHandlingThreads(int)::$_0> >(void*) + 177 (thread:298)
> 24  libsystem_pthread.dylib       	    0x7ff81867e4e1 _pthread_start + 125
> 25  libsystem_pthread.dylib       	    0x7ff818679f6b thread_start + 15
>

2022-10-11 15:37 UTC, pford commented
@kswang1029 I cannot reproduce this crash in my developer build.  Please supply the test image.

2022-10-11 15:42 UTC, kswang1029 commented
> @kswang1029 I cannot reproduce this crash in my developer build. Please supply the test image.

Shared the test image via Slack. Please check

2022-10-12 04:02 UTC, kswang1029 approved these changes
manual tests look good. fix for e2e test is made and no regression is observed. 👍

2022-10-12 09:25 UTC, merged

2022-10-12 09:50 UTC, kswang1029 commented
This requires frontend too

2022-10-12 09:55 UTC, confluence commented
Sorry; I missed that and jumped the gun. If necessary I can revert the merge, but it may not be necessary if the companion PRs are going to be merged soon.

2022-10-12 10:07 UTC, confluence commented
I have reverted this -- as far as I can tell, it's impossible to re-open this PR, so we will either need to open a new PR for this, or to revert the reversion (which may be simpler).