Remove casa CRTF region file parser
CARTAvis/carta-backend pull request #1220
Opened 2022-11-22 21:42 UTC by pford

Closes #1219 .  Use internal implementation for annotation support and performance.

**Description**

* What is implemented or fixed?
When annotation regions are added for #340 , some regions not supported by CRTF externally will need to be imported back into CARTA.  This can only happen using the internal CRTF parser, since the casa CRTF parser will ignore these lines which start with `#`.  As an added bonus, the internal parser can improve performance of importing 20000 regions by 8-10x (#1216 ).

* How does this PR solve the issue?
Removes casa::RegionTextFile from CrtfImportExport import constructor so that the internal parser is always used.  Supporting functions also removed.

* Are there any companion PRs (frontend, protobuf)?
No, backend only.

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
Load various CRTF files and ensure that all regions are imported.

**Checklist**

- [ ] changelog updated
- [ ] e2e test passing
- [ ] no protobuf update needed
- [ ] added reviewers and assignee
- [ ] added ZenHub estimate, milestone, and release

2022-11-22 22:30 UTC, pford commented
Note imageanalysis annotation regions are still used for region export, for proper formatting.  Its use should be reviewed separately.

2022-11-23 07:08 UTC, kswang1029 reviewed
The crtf region import performance is boosted. 🚀


Spotted an e2e test failure due to image coordinate precision. In the dev branch, image coordinate is trimmed/rounded(?) to the first decimal (so the e2e test is designed accordingly). Now with the new parser, that trimming/rounding issue is gone. So I will need to revise the e2e test accordingly. Please allow me some time to perform additional user tests. Overall this PR looks quite promising!

2022-11-23 09:18 UTC, confluence requested changes

2022-11-23 09:18 UTC, confluence commented on src/Region/CrtfImportExport.cc
> +    std::vector<std::string> global_keywords = {"coord", "range", "frame", "corr", "veltype", "restfreq", "linewidth", "linestyle",
Can we change this to a `std::unordered_set` and use its `find` member function? It would avoid the repeated linear lookup.

2022-11-23 15:18 UTC, pford commented on src/Region/CrtfImportExport.cc
> +    std::vector<std::string> global_keywords = {"coord", "range", "frame", "corr", "veltype", "restfreq", "linewidth", "linestyle",
On second thought, I think we should just save the map without checking for keywords.  This was previously a map for the imageanalysis implementation

2022-11-23 17:38 UTC, confluence approved these changes

2022-11-24 02:18 UTC, kswang1029 approved these changes
this should be fine as far as I can tell. 👍 One e2e test is fixed due to the increased precision of parsed image coordinate so when it is converted to angular size, the value for assertion changed.

2022-11-28 12:45 UTC, merged