Yuhsuan/150 model residual image
CARTAvis/carta-backend pull request #1222
Opened 2022-11-30 07:00 UTC by YuHsuan-Hwang

**Description**

This PR is for the 4th and 5th items in #150: generate model/residual images, estimate progress, and listen for cancellation messages.
* Added generating model/residual images
    * Added booleans `create_model_image` and `create_residual_image` to enable the feature.
    * Added `CalculateImageData`: called at the end of the fitting process to obtain model and residual data.
    * Added  `GetGeneratedImages`: for generating model and residual images.
       * The file ids of the generated images are `-1000 * (file id + 1) + 1` and `-1000 * (file id + 1) + 2`. (ex: 0 => -999, -998)
       * If the image is a Carta-generated moment image, the file ids are `-10 * (file id + 1) + 1` and `-10 * (file id + 1) + 2`. (ex: 1002 => -10029, -10028)
       * The filename is `filename_model/residual.extension`.
       * If the image is a Carta-generated moment image, the filename is `filename_model/residual.extension.moment.momentType`.
       * Negative file ids are not supported, i.e. PV images and model/residual images are not supported. This avoids very large file ids which may break frontend tile coordinate encoding.
* Added estimating progress
   * Sends progress message in each fitting iteration.
* Added cancellation
   * The residual will be set to zero in order to force end the fitting process.
* changed: imageFitter now in default logs the parameters in each iterations at the debug level
* Added storing filename of generated images (PV, moment, and model/residual)
   * This is for getting filenames of model/residual images generated from Carta-generated moment images.
   * Added boolean `_is_generated` to replace `filename.empty()` for generated images.
* Added unit tests
   * Tests the generated image size, filename, and file id.
   * Tests if the generated model image is a Gaussian / multiple Gaussians.
   * Tests if the generated residual image is image minus Gaussian / multiple Gaussians.

Companion PRs

**Checklist**

- [ ] changelog updated / no changelog update needed
- [ ] e2e test passing / added corresponding fix
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] added reviewers and assignee
- [ ] added ZenHub estimate, milestone, and release

2022-12-02 10:49 UTC, confluence approved these changes

2022-12-02 22:22 UTC, pford approved these changes

2022-12-02 22:24 UTC, pford commented
I created issue #1224 to improve assigning IDs for generated images, based on comments in the code for this PR.  I have also been uneasy about this.

2022-12-03 02:21 UTC, kswang1029 requested changes
It appears that on the model and residual images, spatial profile generation along a line or a polyline is not working. 

Region analytics, such as histogram and statistics, works fine. Contour rendering and vector field rendering work fine too.

2022-12-05 07:33 UTC, YuHsuan-Hwang commented
> It appears that on the model and residual images, spatial profile generation along a line or a polyline is not working.
> 
> Region analytics, such as histogram and statistics, works fine. Contour rendering and vector field rendering work fine too.

@kswang1029 fixed by allowing negative file ids in region handler.

2022-12-05 15:01 UTC, pford commented on src/Region/RegionHandler.cc
> +    if (((region_id < 0) && (file_id == ALL_FILES)) || (region_id == 0)) { // not allowed
For readability, it might be better to use explicit constants rather than implied ids:
if ((region_id == ALL_REGIONS && file_id == ALL_FILES) || (region_id == CURSOR_REGION_ID))

2022-12-06 03:26 UTC, YuHsuan-Hwang commented on src/Region/RegionHandler.cc
> +    if (((region_id < 0) && (file_id == ALL_FILES)) || (region_id == 0)) { // not allowed
fixed

2022-12-06 04:17 UTC, kswang1029 commented
@YuHsuan-Hwang I found that if we have fitting model and residual images loaded and try to resume a session after reconnecting to the backend, there is a popup window saying resume failed and then a persistent progress bar. The backend console says:

> [2022-12-06 04:12:04.963] [CARTA] [error] File dice_four_model.fits does not exist.
> [2022-12-06 04:12:04.963] [CARTA] [error] File dice_four_residual.fits does not exist. 

This happens to generated PV image as well. We can either fix this in this PR or in another PR. Please advice.

2022-12-07 03:44 UTC, kswang1029 approved these changes
great work 👍 no regression from e2e tests.

2022-12-07 03:46 UTC, YuHsuan-Hwang commented
> @YuHsuan-Hwang I found that if we have fitting model and residual images loaded and try to resume a session after reconnecting to the backend, there is a popup window saying resume failed and then a persistent progress bar. The backend console says:
> 
> > [2022-12-06 04:12:04.963] [CARTA] [error] File dice_four_model.fits does not exist.
> > [2022-12-06 04:12:04.963] [CARTA] [error] File dice_four_residual.fits does not exist.
> 
> This happens to generated PV image as well. We can either fix this in this PR or in another PR. Please advice.
> 
> Otherwise this PR looks good. No regression is observed from e2e tests.

Fixed in the frontend PR. It's related to file id changes, so I expect this still works fine in the release versions.

2022-12-07 03:50 UTC, kswang1029 commented
> > @YuHsuan-Hwang I found that if we have fitting model and residual images loaded and try to resume a session after reconnecting to the backend, there is a popup window saying resume failed and then a persistent progress bar. The backend console says:
> > > [2022-12-06 04:12:04.963] [CARTA] [error] File dice_four_model.fits does not exist.
> > > [2022-12-06 04:12:04.963] [CARTA] [error] File dice_four_residual.fits does not exist.
> > 
> > 
> > This happens to generated PV image as well. We can either fix this in this PR or in another PR. Please advice.
> > Otherwise this PR looks good. No regression is observed from e2e tests.
> 
> Fixed in the frontend PR. It's related to file id changes, so I expect this still works fine in the release versions.

Yes session resume with a generated moment and pv images works.

2022-12-07 06:15 UTC, pford approved these changes

2022-12-07 07:02 UTC, markccchiang approved these changes

2023-01-09 09:12 UTC, merged