Fix the hanging problem of region spectral profiles when a region is deleted
CARTAvis/carta-backend pull request #1330
Opened 2023-11-07 15:57 UTC by markccchiang

**Description**

* What is implemented or fixed? Mention the linked issue(s), if any.
Closes #1328.

* How does this PR solve the issue? Give a brief summary.
This problem is due to the deadlock of two mutexes, `_active_task_mutex` and `_region_mutex`, in the RegionHandler methods. When a region spectral profile process starts, `_active_task_mutex` is taken in the method [GetRegionSpectralData](https://github.com/CARTAvis/carta-backend/blob/dev/src/Region/RegionHandler.cc#L1847). Then the `_region_mutex` will be frequently taken inside this method [RegionFileIdsValid](https://github.com/CARTAvis/carta-backend/blob/dev/src/Region/RegionHandler.cc#L2080) to check whether the region object exists or it is disconnected. If we delete the region during this process, the `RemoveRegion` method is called, and the `_region_mutex` is taken [here](https://github.com/CARTAvis/carta-backend/blob/dev/src/Region/RegionHandler.cc#L113) inside this function. Then it waits to take `_active_task_mutex` in the [WaitForTaskCancellation](https://github.com/CARTAvis/carta-backend/blob/dev/src/Region/RegionHandler.cc#L116). Two methods `GetRegionSpectralData` and `RemoveRegion` are waiting for the same mutexes `_active_task_mutex` and `_region_mutex`. The solution is to remove the `_region_mutex` from the `RegionSet` method. Since it only reads the status of region objects and does not modify the `_regions` map. Removing this mutex allows the [RegionFileIdsValid](https://github.com/CARTAvis/carta-backend/blob/dev/src/Region/RegionHandler.cc#L2080) to get rid of `_region_mutex` (since it can be taken by `RemoveRegion` at the same time), so it can pass the disconnected signal and stop the region spectral profile process. Finally, the region object can be deleted.

* Are there any companion PRs (frontend, protobuf)?
No.

* Is there anything else that testers should know (e.g. exactly how to reproduce the issue)?
The hanging problem of region spectral profiles should be solved.

**Checklist**

- [x] changelog updated ~/ no changelog update needed~
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [x] ~protobuf updated to the latest dev commit /~ no protobuf update needed
- [x] ~protobuf version bumped /~ protobuf version not bumped
- [ ] added reviewers and assignee
- [ ] added ZenHub estimate, milestone, and release

2023-11-21 22:57 UTC, pford requested changes
The purpose of the region mutex is to prevent one thread accessing a region while another is deleting it, and the purpose of the active task mutex is to prevent the region from being destroyed mid-task.  So I think we need them both.

We could move the region mutex lock in RemoveRegion around the regions map: WaitForTaskCancellation then lock-erase-unlock.  For all regions, use an iterator to do this one region at a time.  (1) RemoveRegion disconnects the region and waits for the active task mutex, (2) GetRegionSpectralData uses RegionSet (with a region mutex) to detect that the region exists but is disconnected and exits to release the active task mutex, (3) RemoveRegion safely removes (with a region mutex) the region from the map.

2023-11-22 15:48 UTC, pford approved these changes

2023-11-24 07:11 UTC, kswang1029 approved these changes
Tested. no regression from e2e tests.

2023-11-24 07:50 UTC, confluence approved these changes

2023-11-24 07:50 UTC, merged