Simple omp
CARTAvis/carta-backend pull request #442
Opened 2020-02-20 17:38 UTC by robsimmonds

Replaces Intel TBB parallel_for loops with OpenMP pragmas. 
This code had  been run for a couple of week on the IDIA test server that provides the latest code (usually the dev branch) to IDIA users and seems to have solved a lockup problem we were seeing with the TTB based code.

2020-02-20 21:55 UTC, confluence requested changes
Everything looks fine except for some indentation -- it just needs a formatting pass.

2020-02-20 21:55 UTC, confluence commented on Region/BasicStatsCalculator.tcc
> +			if (val > _max_val) {
Some indentation weirdness; looks like tabs instead of spaces.

2020-02-21 07:00 UTC, veggiesaurus requested changes
@robsimmonds some minor merge conflicts to be fixed.

@ajm-asiaa I see the ubuntu build is failing. Is it ubuntu 16.04? The version of GCC is pretty old (5.4?), and I think that's causing issues with the OpenMP parallel for

2020-02-21 07:47 UTC, ajm-asiaa commented
@veggiesaurus Yes. You are correct. It is Ubuntu 16.04 using gcc version 5.4.0 20160609. I have been using 16.04 to ensure back compatibility. Maybe it is time to move to 18.04, particularly as 20.04 will be out soon. 

So please ignore that it fails on ci/circle: ubuntu for now. Will you still be able to merge it despite the checks failing?

2020-02-21 07:58 UTC, veggiesaurus commented
> @veggiesaurus Yes. You are correct. It is Ubuntu 16.04 using gcc version 5.4.0 20160609. I have been using 16.04 to ensure back compatibility. Maybe it is time to move to 18.04, particularly as 20.04 will be out soon.

Yes, I think it makes sense to move on to supporting 18.04 and 20.04. What about releases in between? I'm on 19.10 at the moment, and things work fine, apart from the casacore repo / hdf5 library mismatch

> So please ignore that it fails on ci/circle: ubuntu for now. Will you still be able to merge it despite the checks failing?

Once the merge conflicts have been fixed, yes.

2020-02-21 08:17 UTC, confluence approved these changes
The formatting issues are fixed.

2020-02-21 09:29 UTC, merged