Support the catalog overlay
CARTAvis/carta-backend pull request #443
Opened 2020-02-21 03:42 UTC by markccchiang

This is for issue #383. The backend support of opening catalog files, parsing and filtering the VOTable data. A few things to be done in the future:

- Add image bounds and region settings in the data filter
- Find a good way to deal with very large files, for example, loading partial data at the first of opening files and then load more data if necessary
- Benchmark the performance

2020-02-21 07:15 UTC, veggiesaurus requested changes
some conflicts with the protobuf changes

Due to complexity of the PR (and the frontend PR), and the build changes required, we should merge them after the code freeze

2020-02-24 08:32 UTC, veggiesaurus commented on Main.cc
> +        group = websocket_hub.createGroup<uWS::SERVER>(uWS::PERMESSAGE_DEFLATE);
I think you can do this without creating a group explicitly, by just passing these arguments to the hub constructor directly.

2020-02-24 08:34 UTC, veggiesaurus commented on Session.cc
> +    _out_msgs.push(std::make_pair(msg, compress));
doesn't this result in an additional copy? you should rather form the pair first, and then serialize to the pair's `msg.data()`

2020-02-24 08:35 UTC, veggiesaurus commented on Session.cc
> +            if (msg.second) { // Compress the message
this can be simplified to just `_socket->send(msg.first.data(), msg.first.size(), uWS::BINARY, nullptr, nullptr, msg.second);`

2020-02-24 15:51 UTC, markccchiang commented
@veggiesaurus I have changed codes by your suggestions. But wondering is it the problem of the frontend's version, the image can not be shown on the viewer on my own test(?)

2020-02-24 16:37 UTC, veggiesaurus commented
> @veggiesaurus I have changed codes by your suggestions. But wondering is it the problem of the frontend's version, the image can not be shown on the viewer on my own test(?)

I noticed that earlier on mix 'n match. Odd.

2020-02-25 03:25 UTC, markccchiang commented
Thanks! With the new version of Qi's catalog branch, the image is back on the viewer.

2020-04-14 10:12 UTC, merged