Jason/spectral line filter
CARTAvis/carta-backend pull request #614
Opened 2020-08-26 01:09 UTC by duidae

companion PR of spectral line filtering

2020-10-06 09:00 UTC, confluence requested changes

2020-10-06 09:00 UTC, confluence commented on SpectralLine/SpectralLineCrawler.cc
> +const std::map<std::string, std::string> SpectralLineCrawler::HeaderTypeMap = {{"Species", "string"}, {"Chemical Name", "string"},
I would suggest formatting this with each key/value pair on a new line -- this style of formatting appears in `Hdf5Loader.cc`, so it should be allowed by `clang-format`.

Also, this should be an `unordered_map`.

2020-10-13 07:18 UTC, confluence approved these changes

2020-10-13 07:31 UTC, duidae commented
@confluence  thanks for reviewing, the frontend part is not done yet, please hold, thanks!

2021-04-13 10:49 UTC, veggiesaurus approved these changes

2021-04-13 10:51 UTC, merged