Additional image support: Concat and CompList and Expr
CARTAvis/carta-backend pull request #666
Opened 2020-11-27 08:32 UTC by zarda

From #388, add image support of CASA Concatenated image, CASA Componentlist image, and CASA Expression.

[Working test link](http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socket5057)

Check list:

- Image type on file list
- File information
- Image readable

Testing image: set_CASAImage_flavors/

2020-12-07 20:22 UTC, pford requested changes

2020-12-07 20:22 UTC, pford commented on ImageData/CompListLoader.h
> +        _num_dims = _image->shape().size();
Should check that _image is not nullptr before using it.

2020-12-07 20:22 UTC, pford commented on ImageData/ConcatLoader.h
> +        _num_dims = _image->shape().size();
Check that _image is not nullptr

2020-12-07 20:22 UTC, pford commented on ImageData/ExprLoader.h
> +        _num_dims = _image->shape().size();
Check _image nullptr

2020-12-08 02:34 UTC, zarda commented
Suggest to load the parent Loader(){ return default... } while child Loader return nullptr.

2020-12-08 15:45 UTC, pford approved these changes

2020-12-08 15:50 UTC, merged