Angus/deprecated threads arg
CARTAvis/carta-backend pull request #703
Opened 2021-01-27 11:26 UTC by veggiesaurus

As requested by @robsimmonds, I've re-introduced the old behaviour of the `threads` argument, because setting the scheduler's thread limit might be required in order to queue blocking messages, rather than trying to handle them all at once.

I've also deferred printing of the frontend URL until the port has been determined.

2021-01-27 15:24 UTC, pford requested changes

2021-01-27 15:24 UTC, pford commented on src/Main.cc
> +            omp_thread_count = inp.getInt("threads");
Inputs assigned to wrong variables

2021-01-27 15:28 UTC, pford requested changes

2021-01-27 15:28 UTC, pford commented on src/Main.cc
> +            thread_count = inp.getInt("omp_threads");
Inputs assigned to wrong variables

2021-01-27 15:45 UTC, veggiesaurus commented on src/Main.cc
> +            thread_count = inp.getInt("omp_threads");
Whoops!

2021-01-28 06:55 UTC, markccchiang approved these changes

2021-01-29 10:23 UTC, merged