Add basic tests for spatial profiles
CARTAvis/carta-backend pull request #841
Opened 2021-06-15 19:50 UTC by confluence

The bulk of this PR is the implementation of test helper classes for reading data directly from a FITS or HDF5 file (to provide expected data for tests). For this test I implemented utility functions for reading a point or a spatial profile, but arbitrary regions can also be read and more utility functions can be added (e.g. for spectral profiles).

I have only implemented two basic tests (for a small FITS and HDF5 file) -- I intend to add many more tests in the mipmaps branch, which introduces mip and range to spatial profile requests, as well as decimation or downsampling of the returned data (with diverging behaviour for FITS and HDF5). Are there any other tests that I should add to this branch now?

@ajm-asiaa this code uses Google Mock, which is part of Google Test, but is provided in a separate binary package (`libgmock-dev`) on Ubuntu (and possibly on other platforms). We need to install the appropriate packages in our containers to get this to compile. I'm also linking to the C++ API for HDF5, but that must already be installed if the converter (added earlier) can compile.

2021-06-15 20:02 UTC, confluence commented
It looks like it's compiling, so I guess the package is already installed. 🤔

2021-06-15 21:04 UTC, veggiesaurus requested changes
Minor comments

2021-06-15 21:04 UTC, veggiesaurus commented on test/CommonTestUtilities.cc
> +    data_space.getSimpleExtentDims(_dims.data(), NULL);
Shouldn't those be nullptr for consistency?

2021-06-15 21:04 UTC, veggiesaurus commented on test/CommonTestUtilities.cc
> +Hdf5DataReader::~Hdf5DataReader() {}
You can replace this with =default in the header

2021-06-15 21:11 UTC, confluence commented on test/CommonTestUtilities.cc
> +    data_space.getSimpleExtentDims(_dims.data(), NULL);
Shouldn't what be nullptr?

2021-06-15 21:15 UTC, confluence commented on test/CommonTestUtilities.cc
> +    data_space.getSimpleExtentDims(_dims.data(), NULL);
You mean that `_imgfile` and `_dataset` should be pointers?

2021-06-15 21:18 UTC, veggiesaurus commented on test/CommonTestUtilities.cc
> +    data_space.getSimpleExtentDims(_dims.data(), NULL);
Sorry, I meant all the NULL arguments should be nullptr instead

2021-06-15 21:21 UTC, confluence commented on test/CommonTestUtilities.cc
> +    data_space.getSimpleExtentDims(_dims.data(), NULL);
Ah, gotcha.

2021-06-16 05:54 UTC, ajm-asiaa approved these changes
@confluence You might have noticed in the beginning there was trouble building the carta_backend on the ubuntu 16.04 system (I know 16.04 is unsupported, but we are currently stuck with that version as it is the only one compatible with our old Lustre disk array system).

I tried installing a more recent googletest version. That fixed the build issue, but then running the tests gave a segmentation fault. I have since tried installing things again, and now everything compiles and runs OK on ubuntu 16.04.

There was also the Jenkins problem last night so I think Jenkins sending the status back to Github is messed up at the moment, but if you check on Jenkins manually, all tests have passed. 

So everything seems to be OK now.

2021-06-17 06:33 UTC, veggiesaurus approved these changes

2021-06-17 06:33 UTC, merged