Use H5Aiterate2 to iterate over HDF5 attributes
CARTAvis/carta-backend pull request #864
Opened 2021-07-02 12:06 UTC by confluence

Should fix #861. I haven't yet tested the performance.

2021-07-02 12:12 UTC, veggiesaurus requested changes

2021-07-02 12:12 UTC, veggiesaurus commented on src/ImageData/Hdf5Attributes.cc
> +    H5Aiterate2(group_hid, H5_INDEX_CRT_ORDER, H5_ITER_INC, NULL, attr_info, &headers);
`NULL` -> `nullptr`

2021-07-02 12:12 UTC, veggiesaurus commented on src/ImageData/Hdf5Attributes.cc
> +    H5Aiterate2(group_hid, H5_INDEX_CRT_ORDER, H5_ITER_INC, NULL, attr_info, &headers);
(and above)

2021-07-02 12:18 UTC, veggiesaurus approved these changes

2021-07-02 12:33 UTC, confluence commented
I see a speed improvement when I load the large test file from SSD. It's still not instantaneous, but definitely much faster than `dev`.

2021-07-02 14:26 UTC, veggiesaurus commented
I can confirm the significant speed improvement over `dev`. For `hlsp_candels_hst_acs_gn-tot-60mas_f606w_v1.0_drz.fits` (13 000 header entries):

FITS (`dev`): 0.65 s
HDF5 (`dev`): 35.1 s
HDF5 (this branch): 2.0 s

2021-07-02 14:33 UTC, veggiesaurus commented
@confluence I've just noticed that `Hdf5Attributes::ReadAttributes` is getting called twice when responding to a single file info. Each time takes around 800 ms, so we could probably improve this quite a bit more. Any idea why its getting called twice?

2021-07-02 14:39 UTC, confluence commented
The first time is when the HDF5 image is opened; the second time is in the info loader, because we don't cache the values. Should be easy to fix; I see no reason not to cache this.

2021-07-02 15:48 UTC, confluence commented
Something weird is happening with the CI tests -- the unit tests are failing on Ubuntu because booleans are being treated as integers. But I tested this on Ubuntu. This looks suspiciously like an architecture-dependent type difference.

2021-07-02 16:04 UTC, confluence commented
I think that this ended up being an [HDF5 library version issue](https://github.com/CARTAvis/carta-backend/pull/750). If we're running these unit tests on Bionic, then we are probably using an old version of the library, which is causing these attributes to be converted incorrectly. Which I now realise is a problem that we may need to fix in the converter, since we are supporting it on Bionic and providing a Bionic package.

2021-07-02 16:12 UTC, confluence commented
This doesn't mean that we can't merge this PR -- it isn't introducing a new bug; it's just exposing one with a new unit test. But the tests should all pass, so I will make a converter issue and prioritise it.

2021-07-02 16:17 UTC, confluence commented
Upon reflection, I think it may be more sensible for us to check for both the old and the new native boolean type. This will allow us to process both old and new files correctly, and there should be no confusion with "real" integer attributes because we use signed 64-bit integers for those. I will update this PR.

2021-07-02 16:45 UTC, confluence commented
I am investigating the failing test on MacOS.

2021-07-02 16:57 UTC, veggiesaurus commented
> The first time is when the HDF5 image is opened; the second time is in the info loader, because we don't cache the values. Should be easy to fix; I see no reason not to cache this.

This branch is down to 1.2 seconds with the caching approach now :rocket: just 30x faster than before :+1:

2021-07-02 16:59 UTC, confluence commented
I think that it would be good to patch the release version with this -- we've just started using the packaged version of the converter on ILIFU, and ILIFU is on Bionic, which means that all our users are about to start making files with the "wrong" booleans.

2021-07-02 17:00 UTC, veggiesaurus commented
> I think that it would be good to patch the release version with this -- we've just started using the packaged version of the converter on ILIFU, and ILIFU is on Bionic, which means that all our users are about to start making files with the "wrong" booleans.

good idea

2021-07-02 17:49 UTC, confluence commented
OK, I've checked, and Bionic is on HDF5 1.10.0. Are we using Xenial in the CI tests?

2021-07-03 08:07 UTC, veggiesaurus commented
I've added @kswang1029 as a reviewer so that he can just do a sanity check and ensure that the set of HDF5 test images still load ok. All the ones that loaded in `dev` still load fine for me in this branch

2021-07-06 05:56 UTC, kswang1029 approved these changes
This works fine as far as I can tell with my hdf5 images.

2021-07-06 14:37 UTC, markccchiang approved these changes

2021-07-06 14:41 UTC, merged