Jason/issue 1130
CARTAvis/carta-backend pull request #870
Opened 2021-07-16 09:29 UTC by duidae

companion PR for https://github.com/CARTAvis/carta-frontend/issues/1130

2021-07-16 09:34 UTC, veggiesaurus commented
Can we not do this alive check on the front-end asynchronously?

2021-07-19 03:40 UTC, duidae commented
> Can we not do this alive check on the front-end asynchronously? The current approaches blocks the backend while it waits for a response.

due to CORS we still need backend to interact with splatalogue, and a 20 sec timeout is added to the ping msg.

2021-07-20 05:32 UTC, kswang1029 approved these changes

2021-07-22 10:10 UTC, veggiesaurus approved these changes
looks ok to me. Just waiting for protocol buffer PR reviews then we can merge. @ajm-asiaa not sure why the ICD tests are failing here :thinking:

2021-07-22 10:23 UTC, ajm-asiaa commented
> looks ok to me. Just waiting for protocol buffer PR reviews then we can merge. @ajm-asiaa not sure why the ICD tests are failing here 🤔

It is the segmentation fault of carta_backend_tests on MacOS. I still haven't figured out the reason yet...

2021-07-22 10:23 UTC, veggiesaurus requested changes

2021-07-22 10:23 UTC, veggiesaurus commented on src/Session.cc
> +void Session::OnSplataloguePing(CARTA::SplataloguePing splatalogue_ping, uint32_t request_id) {
`splatalogue_ping` is unused, we don't need to pass it here.

2021-07-22 10:23 UTC, veggiesaurus commented on src/OnMessageTask.h
> +    OnSplataloguePingTask(Session* session, CARTA::SplataloguePing message, uint32_t request_id) : OnMessageTask(session) {
`_message` is unused

2021-07-22 10:23 UTC, veggiesaurus commented on src/OnMessageTask.cc
> +    _session->OnSplataloguePing(_message, _request_id);
only need `_request_id`

2021-07-23 09:25 UTC, veggiesaurus approved these changes

2021-07-23 09:54 UTC, merged