797 ICD tests in the backend unit tests
CARTAvis/carta-backend pull request #888
Opened 2021-08-03 18:20 UTC by markccchiang

This PR is the trial for #797 to move some ICD tests back to the backend unit tests. The ICD testing codes are in the new folder `test/icd_test`. A new executable file `carta_backend_icd_tests` will be generated to run ICD tests independently. Since the [original ICD tests](https://github.com/CARTAvis/carta-backend-ICD-test) use some image samples with large sizes, I do not include these images in the backend repo. Users need to copy these images manually to run the test. So far a simple framework for of ICD test is roughly done. I will add more testing cases according to the [document](https://docs.google.com/spreadsheets/d/1qwdTTKdNA1oNnNAUNgyPZH5HOVyt2Uw0vPT2_UsEaXk/edit#gid=0)).

2021-08-03 19:31 UTC, veggiesaurus commented
> Since the [original ICD tests](https://github.com/CARTAvis/carta-backend-ICD-test) use some image samples with large sizes, I do not include these images in the backend repo. Users need to copy these images manually to run the test

We can automatically generate these images. Please follow the implementation @confluence used.

I also think we don't have to strictly keep the same test approach, that's not the point of this migration. If something can be tested simply as a unit test (e.g. Does Carta generate the correct file information?) then there's really no need to wrap it in then entire ICD. Just test the functionality.

Some examples that would make trivial unit tests and not require any specific ICD stuff (although that will be useful for certain tests)

- histograms
- file lists
- file info
- contours
- region stats
- moment maps
- saved images

2021-08-04 13:27 UTC, confluence commented
Agreed -- tests which confirm that each message has an expected and well-formed response should remain as ICD tests. Tests which check the _correctness_ of the data should be removed from the ICD tests and rewritten as ordinary unit tests which bypass the messaging interface and call functions in the backend objects directly. Wherever possible we should use generated images.

2021-09-06 02:21 UTC, markccchiang commented
Now I tried to integrate ICD testing codes with current backend codes. The `Session` class is modified so it can remove the correlation with uWebSockets. Refactored protobuf messages handlers on `OnMessageTask` and `Main.` Decoding incoming messages are only done in the `Main.` Added a new folder `Util` and moved `Util.h/.cc` to this folder. Also, I created new `ProtobufUtilities.h/.cc` for creating or filling protobuf messages helpers. As for the rest of the ICD tests, I will continue them in another PR.

2021-09-10 06:49 UTC, ajm-asiaa commented
I get a segmentation fault when I try to run it on MacOS:

```
./carta_backend_icd_tests       
[==========] Running 14 tests from 11 test cases.
[----------] Global test environment set-up.
[----------] 1 test from TestAnimatorPlayback
[ RUN      ] TestAnimatorPlayback.ANIMATOR_PLAYBACK
2021-09-10 06:44:41	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
zsh: segmentation fault  ./carta_backend_icd_tests
```

Maybe the images are missing? 
> Users need to copy these images manually to run the test.

Is there a list of images that are required?

2021-09-10 07:13 UTC, ajm-asiaa commented
I forgot that the ordinary unit tests have a problem on MacOS. When I run `./carta_backend_tests`, sometimes they pass, sometimes I get `zsh: segmentation fault  ./carta_backend_tests`, so it is not an exclusive issue with `./carta_backend_icd_tests`. I will just test using Linux instead.

2021-09-10 07:58 UTC, ajm-asiaa commented
I have run it several times in an Ubuntu 20.04 Docker container. It is a good start, but unfortunately, just like the old ICD tests, they seem to be unable consistently pass every time. Sometimes all 14 tests pass, other times some fail. For example, I have got:

```
[ RUN      ] TestAnimatorPlayback.ANIMATOR_PLAYBACK
2021-09-10 07:44:33	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
/root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
Expected equality of these values:
  sync_channel
    Which is: 10
  expected_channel
    Which is: 18
/root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
Expected equality of these values:
  sync_channel
    Which is: 10
  expected_channel
    Which is: 17
/root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
Expected equality of these values:
  sync_channel
    Which is: 9
  expected_channel
    Which is: 16
/root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
Expected equality of these values:
  sync_channel
    Which is: 18
  expected_channel
    Which is: 15
/root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:204: Failure
Expected equality of these values:
  message_count
    Which is: 76
  expected_response_messages
    Which is: 33
[  FAILED  ] TestAnimatorPlayback.ANIMATOR_PLAYBACK (680 ms)
```

```
[ RUN      ] TestRegionSpectralProfileRectangle.REGION_SPECTRAL_PROFILE_RECTANGLE
2021-09-10 07:44:43	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
/root/carta-backend/test/icd-test/TestRegionSpectralProfileRectangle.cc:135: Failure
Expected equality of these values:
  message_count
    Which is: 2
  1
[  FAILED  ] TestRegionSpectralProfileRectangle.REGION_SPECTRAL_PROFILE_RECTANGLE (15 ms)
```

```
[ RUN      ] TestAnimatorPlayback.ANIMATOR_PLAYBACK
2021-09-10 07:47:06	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
/root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
Expected equality of these values:
  sync_channel
    Which is: 18
  expected_channel
    Which is: 19
/root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:204: Failure
Expected equality of these values:
  message_count
    Which is: 17
  expected_response_messages
    Which is: 33
[  FAILED  ] TestAnimatorPlayback.ANIMATOR_PLAYBACK (663 ms)
```

I also happened to get `Segmentation fault (core dumped)` and a time when it seemingly got stuck. I guess this will be hard to debug.

Are you planning to add the --gtest command line flags like the ones we see when we do `./carta_backend_tests --help` so that we can focus on certain tests?

2021-09-10 08:06 UTC, kswang1029 commented
> I have run it several times in an Ubuntu 20.04 Docker container. It is a good start, but unfortunately, just like the old ICD tests, they seem to be unable consistently pass every time. Sometimes all 14 tests pass, other times some fail. For example, I have got:
> 
> ```
> [ RUN      ] TestAnimatorPlayback.ANIMATOR_PLAYBACK
> 2021-09-10 07:44:33	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
> /root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
> Expected equality of these values:
>   sync_channel
>     Which is: 10
>   expected_channel
>     Which is: 18
> /root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
> Expected equality of these values:
>   sync_channel
>     Which is: 10
>   expected_channel
>     Which is: 17
> /root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
> Expected equality of these values:
>   sync_channel
>     Which is: 9
>   expected_channel
>     Which is: 16
> /root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
> Expected equality of these values:
>   sync_channel
>     Which is: 18
>   expected_channel
>     Which is: 15
> /root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:204: Failure
> Expected equality of these values:
>   message_count
>     Which is: 76
>   expected_response_messages
>     Which is: 33
> [  FAILED  ] TestAnimatorPlayback.ANIMATOR_PLAYBACK (680 ms)
> ```
> 
>  ```
> [ RUN      ] TestRegionSpectralProfileRectangle.REGION_SPECTRAL_PROFILE_RECTANGLE
> 2021-09-10 07:44:43	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
> /root/carta-backend/test/icd-test/TestRegionSpectralProfileRectangle.cc:135: Failure
> Expected equality of these values:
>   message_count
>     Which is: 2
>   1
> [  FAILED  ] TestRegionSpectralProfileRectangle.REGION_SPECTRAL_PROFILE_RECTANGLE (15 ms)
> ```
> 
>  ```
> [ RUN      ] TestAnimatorPlayback.ANIMATOR_PLAYBACK
> 2021-09-10 07:47:06	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
> /root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:189: Failure
> Expected equality of these values:
>   sync_channel
>     Which is: 18
>   expected_channel
>     Which is: 19
> /root/carta-backend/test/icd-test/TestAnimatorPlayback.cc:204: Failure
> Expected equality of these values:
>   message_count
>     Which is: 17
>   expected_response_messages
>     Which is: 33
> [  FAILED  ] TestAnimatorPlayback.ANIMATOR_PLAYBACK (663 ms)
> ```
> 
> I also happened to get `Segmentation fault (core dumped)` and a time when it seemingly got stuck. I guess this will be hard to debug.
> 
> Are you planning to add the --gtest command line flags like the ones we see when we do `./carta_backend_tests --help` so that we can focus on certain tests?

@markccchiang do you use FPS=5 for the animator test? If so could you try FPS=2 instead so that minimal cpu resource is required. I see a similar problem with robot test too.

2021-09-10 08:18 UTC, veggiesaurus requested changes
@markccchiang I thought we agreed that you would integrate things into the existing unit tests for this PR? And just include a single additional test in this PR that makes use of the backend model stuff?

Many of the tests here are still simply ICD tests being run on the backend instead of via the frontend. We want to migrate many of these tests to real unit tests, that just tests the functionality. For example, region stats should be just testing the actual region stats part of the code, not the full ICD.

Are there still image files required, or are you only using generated files?

2021-09-10 08:18 UTC, veggiesaurus commented on test/icd_test/BackendTester.h
> +class ElapsedTimer {
We already have a timer class, with it's own set of unit tests.

2021-09-10 14:10 UTC, markccchiang commented
> @markccchiang I thought we agreed that you would integrate things into the existing unit tests for this PR? And just include a single additional test in this PR that makes use of the backend model stuff?
> 
> Many of the tests here are still simply ICD tests being run on the backend instead of via the frontend. We want to migrate many of these tests to real unit tests, that just tests the functionality. For example, region stats should be just testing the actual region stats part of the code, not the full ICD.
> 
> Are there still image files required, or are you only using generated files?

Sorry for that! I think I missed your point in the discussion last time. Will change the code and use a single additional test that makes use of the backend model. Now I only use generated files in ICD tests.

2021-09-10 14:57 UTC, markccchiang commented
@ajm-asiaa Sometimes I also get segmentation fault when running `./carta_backend_tests` or `./carta_backend_icd_tests`. The problem of `ANIMATOR_PLAYBACK` and `REGION_SPECTRAL_PROFILE_RECTANGLE` also happens in my test. I guess there is something wrong when parallelizing these computations. But in the unit test definition, as @veggiesaurus mentioned that we only test the functionality. There is no problem from this point of view. It is a good idea that adds command line flags to only run some specific tests. I will try it.

2021-09-13 03:12 UTC, ajm-asiaa commented
@markccchiang Nice work. It runs fairly well after testing on Ubuntu 20.04. Sometimes I still get the segmentation fault, even when only running the new tests e.g `./carta_backend_tests --gtest_filter=TestIcd*  --gtest_repeat=50 --gtest_shuffle`, but I know it is not related to these new tests in particular so probably out of the scope of this pull request.

I think you noticed the issue on Jenkins with MacOS last night:

```
> OMP: Error #131: Thread identifier invalid.
> OMP: Error #131: Thread identifier invalid.
> OMP: Error #131: Thread identifier invalid.
> OMP: Error #131: Thread identifier invalid.
```

I looked it up and luckily found the solution [here](https://github.com/microsoft/LightGBM/issues/4229). It is a known issue and is apparently due to a bug in Homebrew's current libomp 12.0.1 on Big Sur (MacOS 11) only. Their suggested solution is to downgrade to the older libomp version 11 for now. I have done so, and now the tests pass on MacOS CI again.

2021-09-13 03:21 UTC, ajm-asiaa commented
@markccchiang  I have one suggestion. I'm not sure what everyone else thinks? @veggiesaurus? I know the ICD test names were previously in capital letters for some reason, but would it be worth renaming them to capital and lower case (plus without underscores) so that they would be consistent with the rest of the Unit Test test names?
```
HistogramTest.
  TestHistogramBehaviour
  TestHistogramConstructor
  TestHistogramAdd
  TestSingleThreading
  TestMultithreading
TestIcd.
  ACCESS_CARTA_DEFAULT
  ACCESS_CARTA_KNOWN_DEFAULT
  ACCESS_CARTA_NO_CLIENT_FEATURE
  ACCESS_CARTA_SAME_ID_TWICE
  ANIMATOR_DATA_STREAM
  ANIMATOR_NAVIGATION
  ANIMATOR_PLAYBACK
  REGION_REGISTER
MomentTest.
  CheckConsistency
  CheckConsistencyForBeamConvolutions
```

2021-09-14 12:23 UTC, confluence requested changes
This PR now contains too many unrelated and significant changes. I think that we should split out the message wrapper class into its own PR, and review and merge that separately.

We can review that change in more detail in that PR, but in brief I would suggest that you rename the file of wrappers from `ProtobufUtilities` to `Message`, make all the wrapper functions static functions on a `Message` class, and rename them to have the same name as the message: e.g. `Message::RegisterViewer` should return a `CARTA::RegisterViewer`.

It's fine to put it in a `Util` subdirectory for now; this is consistent with the approach I'm currently taking to refactor `Util` into separate files. But please don't move `Util.h` and `Util.cc` into the subdirectory; it's an unnecessary change, and these files are being eliminated anyway.

In that PR we should also update the rest of the code to use these wrappers consistently to construct messages. This should also include replacing the three `Fill...` functions with functions which return messages.

2021-09-16 02:12 UTC, markccchiang commented
Convert this PR to draft. I will reopen it after the code change about the message wrapper is merged into dev.

2021-09-16 07:20 UTC, confluence commented
For clarity, I was also requesting that you move `Util/Message.*` and the associated changes into a separate PR.

2021-10-29 10:19 UTC, confluence requested changes

2021-10-29 10:19 UTC, confluence commented on src/Session.cc
> +}
Rather than adding these functions to the main Session class, please make `_out_msgs` protected, and create a subclass of Session in the test code which has functionality that is only used from tests. This is more consistent with our current approach -- see for example `TestFrame` and `TestSimpleFrontendServer`.

2021-11-11 15:44 UTC, confluence approved these changes
I think that this is all fine now. I'm not 100% sure if we should be making *all* private members of `Session` protected, but I don't have a specific objection.

2021-11-12 03:07 UTC, pford commented
> I also think we don't have to strictly keep the same test approach, that's not the point of this migration. If something can be tested simply as a unit test (e.g. Does Carta generate the correct file information?) then there's really no need to wrap it in then entire ICD. Just test the functionality.
> 
> Some examples that would make trivial unit tests and not require any specific ICD stuff (although that will be useful for certain tests)
> 
>     * histograms
>     * file lists
>     * file info
>     * contours
>     * region stats
>     * moment maps
>     * saved images

I am confused by this PR and the issue comments.  This test framework is very high-level at the message received/response level, rather than as close as possible to the code which does the work.  I thought the goal was not to duplicate the ICD tests?

2021-11-12 07:41 UTC, confluence commented
My understanding is that we decided that it was a good idea to have one specific unit test which tests the Session's message handling (which is what this PR currently contains) and to add most of the converted tests (the original purpose of this PR) in stages, in multiple PRs, rather than adding them in one large PR. But perhaps one group of tests should be selected to be added to this PR, so that we can further discuss the approach here.

2021-11-12 15:04 UTC, markccchiang commented
> I am confused by this PR and the issue comments. This test framework is very high-level at the message received/response level, rather than as close as possible to the code which does the work. I thought the goal was not to duplicate the ICD tests?

I agree that some tests can just be trivial unit tests. We don't need to duplicate the original ICD tests. We can simplify and migrate some ICD tests to the backend so that we can inspect in detail why some of the original ICD tests failed, like animation and moments generation. The main purpose of high-level tests is to check if the message received/response fits our expectations (in case if we want to do this kind of test for the new feature without the frontend). I think it can also be used to test the performance in the future. I will check if some of the test cases can be removed. Or just leave it as an example for the developer who wants to add more tests (@acdo2002 seems to have the interest to do it).

2021-11-13 00:59 UTC, pford approved these changes

2021-11-15 08:10 UTC, acdo2002 commented
I have test the ICD unit tests on the Ubuntu 20.04.
(1) After the tests, the carta_backend_test stuck there, for example:
```
[==========] 7 tests from 1 test suite ran. (5523 ms total)
[  PASSED  ] 7 tests.


```
(2) Some problem with AnimatorNavigation:

> mingyi@mingyi-ASUS-ExpertCenter-D900TA-M900TA:~/carta-backend-unit/build/test$ ./carta_backend_tests --gtest_filter=IcdTest.*
> Note: Google Test filter = IcdTest.*
> [==========] Running 8 tests from 1 test suite.
> [----------] Global test environment set-up.
> [----------] 8 tests from IcdTest
> [ RUN      ] IcdTest.AccessCartaDefault
> [       OK ] IcdTest.AccessCartaDefault (1 ms)
> [ RUN      ] IcdTest.AccessCartaKnownDefault
> [       OK ] IcdTest.AccessCartaKnownDefault (0 ms)
> [ RUN      ] IcdTest.AccessCartaNoClientFeature
> [       OK ] IcdTest.AccessCartaNoClientFeature (0 ms)
> [ RUN      ] IcdTest.AccessCartaSameIdTwice
> [       OK ] IcdTest.AccessCartaSameIdTwice (0 ms)
> [ RUN      ] IcdTest.AnimatorDataStream
> 2021-11-15 07:23:31	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis
> [       OK ] IcdTest.AnimatorDataStream (456 ms)
> [ RUN      ] IcdTest.AnimatorNavigation
> sh: 1: fits2idia: not found
> sh: 1: fits2idia: not found
> /home/mingyi/carta-backend-unit/test/TestIcd.cc:191: Failure
> Expected equality of these values:
>   _message_count
>     Which is: 1
>   3
> /home/mingyi/carta-backend-unit/test/TestIcd.cc:205: Failure
> Value of: open_file_ack.success()
>   Actual: false
> Expected: true
> /home/mingyi/carta-backend-unit/test/TestIcd.cc:220: Failure
> Expected equality of these values:
>   _message_count
>     Which is: 1
>   2
> /home/mingyi/carta-backend-unit/test/TestIcd.cc:242: Failure
> Expected equality of these values:
>   _message_count
>     Which is: 1
>   4
> /home/mingyi/carta-backend-unit/test/TestIcd.cc:264: Failure
> Expected equality of these values:
>   _message_count
>     Which is: 1
>   4
> [  FAILED  ] IcdTest.AnimatorNavigation (512 ms)
> [ RUN      ] IcdTest.AnimatorPlayback
> 2021-11-15 07:23:32	INFO	FITSCoordinateUtil::fromFITSHeader	passing empty or nonexistant spectral Coordinate axis

2021-11-15 08:33 UTC, markccchiang commented
> > [       OK ] IcdTest.AnimatorDataStream (456 ms)
> > [ RUN      ] IcdTest.AnimatorNavigation
> > sh: 1: fits2idia: not found
> > sh: 1: fits2idia: not found
Looks like you do not install the `fits2idia` executor?

2021-11-15 09:13 UTC, acdo2002 commented
@markccchiang Yes, you are right, after I install fits2idia, the (2) problem disappears!!
but (1) is still there with Ubuntu 20.04....

2021-11-15 20:12 UTC, veggiesaurus approved these changes
will merge in once the CI shows all tests passing

2021-11-16 07:38 UTC, merged