matrix style Jenkinsfile
CARTAvis/carta-backend pull request #919
Opened 2021-09-13 07:44 UTC by ajm-asiaa

@veggiesaurus I think it is about time to switch to the new Jenkinsfile. This will free up our existing Ubuntu server so I'll finally be able to upgrade it and use it for frontend ICD testing in parallel. 

Here is some information:

- All the four supported Linux systems are now run through Docker containers on a single AMD server. Test images are read from an internal SSD.

- Due to CentOS8 reaching EOL soon and the fact that things might look complicated if I continue to use CentOS7 with either AlmaLinux or Rocky Linux, I decided to switch to actual RHEL. So now we are using real RHEL7 and RHEL8 Docker containers created from the RedHat Universal Base Images (UBI).

- I know we support two macOS versions, but we only have one Intel MacMini with Big Sur available at present. The backend build, unit tests, and ICD tests run natively on it. We plan to purchase a 2nd Intel MacMini shortly, perhaps for when macOS Monterey comes out as it will be easier to upgrade Monterey rather than downgrade Big Sur to Catalina. At that time we will cover the latest two macOS versions; 11 and 12.

- There is an annoying limit to the size of a declarative pipeline in a Jenkinsfile. Even after moving as many lines as possible into definition blocks, the file is still too large to be parsed when covering the 5 systems. Therefore, I have had to use 'matrix' style of configuration. Unfortunately, it is not visualised very well by Blue Ocean. I have tried to make it as clear as possible. The first 3 stages (Build, Unit Tests, and prepare ICD tests) are kept in the old way. The ICD tests themselves appear in a single stage. Throughout that stage, it is not clear which row represents which OS. They don't line up with those of the first column. But you can find out by inspecting the stage or remembering that they are in alphabetical order (bionic, focal, macos11, rhel7, rhel8). I tried to put the first 3 stages in the same order, but I have their names more explicit e.g. Ubuntu 20.04. I needed to use shorter single word names for the matrix variable.

- As before, if an ICD test fails, it waits 30 seconds and runs the test again, using the same backend process. Also, when a test fails, it runs `cat /root/.carta/log/carta.log`. Hopefully both may be helpful in some cases, but hasn't been useful so far.

- There is a very strange issue where a few ICD tests fail on the Ubuntu 20.04 Docker container when run through Jenkins. They do not fail when I run them manually in the same container. Plus they work fine in the three other Docker containers when Jenkins runs them. I decided to temporarily remove them but I have made an issue in the ICD test repository [#277](https://github.com/CARTAvis/carta-backend-ICD-test/issues/277)

- We have discovered a carta-backend bug occurring only on RHEL8/CentOS8 regarding region files. It causes the backend to crash. We have filed a backend issue [#909](https://github.com/CARTAvis/carta-backend/issues/909).  I thought I would leave the failing test in for now. Hopefully it could be fixed soon.

- I decided to add macOS Unit Tests back. Using the older hdf5@1.10 actually appears to prevent the previous HDF5 problems.

- The list of ICD tests are still hard coded into the Jenkinsfile, so it is not so easy to change tests or add more as it would then need to be merged into every existing branch.

- In the case of @markccchiang's branch [PR#888  ](https://github.com/CARTAvis/carta-backend/pull/888), and future additions, I guess we could modify the Jenkinsfile in the same pull request to remove the duplicated tests from the Jenkinsfile. e.g. Session and Animator.

2021-09-13 07:52 UTC, veggiesaurus requested changes
I'm out of my depth WRT jenkins itself, but I spotted a couple of minor formatting issues

2021-09-13 07:52 UTC, veggiesaurus commented on Jenkinsfile
> +        stage ('Build') {
formatting inconsistency.

2021-09-13 07:52 UTC, veggiesaurus commented on Jenkinsfile
> +                stage('Ubuntu 20.04') {
whitespace

2021-09-13 07:52 UTC, veggiesaurus commented on Jenkinsfile
> +def prepare_focal_ICD() {
newline?

2021-09-13 07:58 UTC, kswang1029 reviewed
we are using `--omp_threads 8` for all OSs. This means in parallel, we will use 32 (8x4) in one single AMD server. Is this correct?

2021-09-13 13:13 UTC, ajm-asiaa commented
@veggiesaurus Thanks. I tried to address the formatting issues.

On MacOS, I noticed a problem where it tries to run `cat /root/.carta/log/carta.log` but fails because there is no log file there. Now I realise MacOS would write to `/Users/<username>/.carta/log`. As I'm using the matrix style configuration, it is not easy to have different parameters for different systems. However, I went through a similar situation for the `/images` directory. On MacOS, we can't make folders in the root directory. But I found a handy way to create symlinks to the root directory on [Stackoverflow](https://stackoverflow.com/questions/58396821/what-is-the-proper-way-to-create-a-root-sym-link-in-catalina) using a `/etc/synthetic.conf` file. I have added /root symlink to it now, so our file looks like this (In that file make sure to use a tab instead of spaces) and the problem is fixed.

```
images  Users/acdc/almalustre-images
root    Users/acdc
```

I have also decided to remove the MacOS unit tests again because from these few attempts, they still tend to fail more often than not.

@kswang1029 Yes. For each Linux Docker container, I let them build the backend using 16 cores, and run the backends with 8 cores. So yes, during the ICD tests, it should be using 32 cores in total. That is fine as it is a 2x24 core CPU server, plus there should be no other users (For MacOS, the resources are more limited, so I only let it build with 8 cores and run with 8 cores).

If you consider RAM usage, that is not an issue either. The server has 128GB. I have monitored it using `docker stats`. During the backend build process, no single Docker container has used more than 12% of the RAM at any one time. During the Unit Tests and ICD tests, I haven't observed it going any higher than 1.6% memory usage per container.

2021-09-13 13:21 UTC, ajm-asiaa commented
Another disadvantage of the matrix configuration in the Jenkinsfile is that now all the ICD tests appear grouped into one stage on Github. For example:

![Screen Shot 2021-09-13 at 9 17 15 PM](https://user-images.githubusercontent.com/20802551/133090441-6f4c8973-11b9-48b1-a053-3613d185d45f.png)

So you need to go and click "Details" to see which ones failed. 

Previously each stage of ICD test appeared on separate rows:

![Screen Shot 2021-09-13 at 9 19 51 PM](https://user-images.githubusercontent.com/20802551/133090850-da6d977a-e531-48d1-afdd-40797043013e.png)

But I can't figure out any other way of doing it.

2021-09-13 13:59 UTC, veggiesaurus commented
@ajm-asiaa isn't that what env variables are for?

2021-09-14 02:51 UTC, ajm-asiaa commented
@veggiesaurus Good point. I guess that could have been an alternative. But are both be solutions to the same problem. You can see that the `/etc/synthetic.conf` method is working perfectly fine.

2021-10-13 11:49 UTC, veggiesaurus approved these changes

2021-10-13 11:58 UTC, closed without merging