Refactor messages handlers on the Main and OnMessageTask
CARTAvis/carta-backend pull request #920
Opened 2021-09-16 06:48 UTC by markccchiang

This is the part of code changes on #888. I refactored messages handlers from the Main and OnMessageTask. The incoming protobuf messages are decoded only on the Main. And a new `GeneralMessageTask` from the OnMessageTask handles messages based on the protobuf message type. The `MultiMessageTask` is removed. It allows the backend ICD testers to create a testing message without encoding/decoding steps.

2021-09-16 07:07 UTC, veggiesaurus requested changes

2021-09-16 07:07 UTC, veggiesaurus commented on src/Main.cc
> +                        spdlog::warn("Bad {} message!", event_type_name);
Since we're refactoring things anyway, I'd prefer to get rid of all this repetition. What about having a `bool message_parsed = false` that gets set to `true` in each `if (message.ParseFromArray(...)) {` branch?

And then at the end we can just have a single `spdlog::warn`. That way, if we want to change how it is formatted, we only need to change one line

2021-09-16 07:07 UTC, veggiesaurus commented on src/OnMessageTask.h
> +template <typename T>
please move this and the rest of the function implementations into a `.tcc` file for consistency with the rest of the codebase

2021-09-17 08:03 UTC, veggiesaurus approved these changes

2021-09-21 13:24 UTC, confluence approved these changes

2021-09-22 07:03 UTC, merged