Use cfitsio for FITS headers
CARTAvis/carta-backend pull request #937
Opened 2021-10-14 23:04 UTC by pford

Closes #912 

Workaround for casacore::ImageFITSConverter::ImageHeaderToFITS, which loses the index _n_ on headers CXXXXn (for example CTYPE1, CRPIX2, CUNIT3, CROTA2).  They are returned in order so we have been incrementing _n_ for each header name each time it appears.  However, there is no way to guess _n_ for CROTAn which is not in order.

Instead, we will use native libraries where possible to create the header entries: (1) HDF5 for HDF5 images (retrieved from CartaHdf5Image) and (2) cfitsio for FITS images (retrieved from CartaFitsImage, and generated in FileExtInfoLoader for casacore::FITSImage),  but continue to convert images to headers using casacore as before for CASA and MIRIAD images.

Tested using the image in issue #912 by verifying the CROTA2 header keyword and the WCS grid on the loaded image.

2021-10-16 04:54 UTC, pford commented
Both tests fail due to additional header entries.  @kswang1029 do you want the COMMENT and HISTORY headers shown in the file browser and File Header widget?

2021-10-16 05:32 UTC, kswang1029 commented
> Both tests fail due to additional header entries. @kswang1029 do you want the COMMENT and HISTORY headers shown in the file browser and File Header widget?

Yes please. This would be ideal and consistent with ds9

2021-10-20 16:20 UTC, pford commented
I enabled history for ImageHeaderToFITS used for CASA and MIRIAD images; already included for HDF5 and FITS in this branch.

2021-10-29 03:13 UTC, kswang1029 commented
@pford @veggiesaurus Got an issue loading an image (see link). The image loads but the WCS grid cannot be rendered properly. It appears that with this backend change, the frontend needs to be updated too to accommodate some exceptional (non-standard?) wcs headers. 

https://drive.google.com/file/d/1mxo4YO6H7zLq9T1eZnHBnGpfe1ITKoEl/view?usp=sharing

![Screen Shot 2021-10-29 at 11 13 38 AM](https://user-images.githubusercontent.com/20819712/139368081-077b3a37-08cd-4ed5-b56e-38ca5bf9db4e.png)

2021-10-29 18:09 UTC, pford commented
This is a backend error.  It is reading the primary header.

2021-11-01 23:05 UTC, pford commented
@kswang1029 I fixed the header issue, please re-test.

2021-11-02 05:50 UTC, kswang1029 approved these changes
Have tried FITS images in our test image pool and it works fine as far as I can tell. 👍

2021-11-02 10:50 UTC, confluence requested changes

2021-11-02 10:50 UTC, confluence commented on src/FileList/FileExtInfoLoader.cc
> +                break;
1. It looks like the calculated `string_value` not actually being used in any of these cases.
2. Would it be possible to refactor this case statement to move the common elements of the `header_entry` creation outside?

2021-11-02 19:38 UTC, confluence approved these changes

2021-11-02 20:00 UTC, veggiesaurus commented
this looks good. @kswang1029 I guess we just need to update the ICD tests now, since the `HISTORY` headers are parsed correctly as of this PR.

2021-11-02 20:00 UTC, merged