Yuhsuan/895 hypercube types
CARTAvis/carta-backend pull request #942
Opened 2021-10-18 09:06 UTC by YuHsuan-Hwang

This PR is for the second part of #895:
1. Extended the types of hypercube:
apply a general check of the FITS stokes axis;
convert `CARTA::PolarizationType` to `casacore::Stokes`;
apply error handling for `stokesCoordinate()`.
2. Fixed issues when reading stokes info from the header:
allow `CTYPE` to be "Stokes" or "stokes" for CASA and FITS images;
get stokes indices using `CRPIX`, `CRVAL`, and `CDELT` to correctly read headers with `CRPIX != 1`;
convert FITS index to CARTA::PolarizationType.

requires frontend branch: `yuhsuan/1606_hypercube_types`

2021-10-18 10:40 UTC, confluence requested changes
I would prefer to avoid putting anything in `Util` unnecessarily -- it should only be required if a function is used in multiple files which do not and should not depend on each other.

`GetCasaStokesType` is only used by `StokesFilesConnector`, so I think that it should be defined in that header (and if we do decide to put it in `Util`, for consistency it should go in `Util/Casacore`).

`ConvertFitsStokesValue` could be defined in the `FileLoader` header, since `StokesFilesConnector` imports it.

Apart from that, I think this all looks good.

2021-10-19 06:18 UTC, YuHsuan-Hwang commented
@confluence I moved the functions to `StokesFilesConnector.h` and `FileLoader.h`. Please check, thanks!

2021-10-19 07:13 UTC, confluence approved these changes

2021-10-19 14:53 UTC, markccchiang approved these changes

2021-10-29 04:41 UTC, kswang1029 approved these changes
this works well 👍

2021-11-11 09:33 UTC, merged