additional error handling when checking for file existence
CARTAvis/carta-backend pull request #946
Opened 2021-10-20 19:15 UTC by veggiesaurus

Closes #945 by adding additional error handling when calling `fs::exists`

2021-10-27 09:36 UTC, confluence commented on src/Util/App.cc
> +    if (fs::exists(path, error_code) && !error_code, fs::is_regular_file(path)) {
Should this be `&&` and not `,`?

2021-10-27 09:36 UTC, confluence commented on src/Table/Table.cc
>          _parse_error_message = "File does not exist!";
Should we print a more specific message if there is an error code?

2021-10-27 09:36 UTC, confluence commented on src/SessionManager/ProgramSettings.cc
> +    no_system_config = result.count("no_system_config") != 0;
Can you assign an integer directly to boolean? If yes, why not just do that instead? Or cast to boolean?

2021-10-27 10:53 UTC, veggiesaurus commented on src/Util/App.cc
> +    if (fs::exists(path, error_code) && !error_code, fs::is_regular_file(path)) {
how did it even compile with that typo? :see_no_evil:

2021-10-27 10:55 UTC, kswang1029 commented on src/Util/App.cc
> +    if (fs::exists(path, error_code) && !error_code, fs::is_regular_file(path)) {
Eyeballing compiler😆

2021-10-27 10:55 UTC, veggiesaurus commented on src/Util/App.cc
> +    if (fs::exists(path, error_code) && !error_code, fs::is_regular_file(path)) {
huh, I'll be damned: https://en.wikipedia.org/wiki/Comma_operator

2021-10-27 10:58 UTC, veggiesaurus commented on src/Table/Table.cc
>          _parse_error_message = "File does not exist!";
I've just added `or cannot be read` here. Digging into the filesystem error codes would be beyond the scope, I think

2021-10-27 11:01 UTC, veggiesaurus commented on src/SessionManager/ProgramSettings.cc
> +    no_system_config = result.count("no_system_config") != 0;
we use `!= 0` quite a bit in the codebase, so I figured I'd keep it in. The really unneccessary part was the `? true : false` bit, since it's basically saying `if (true) return true; else return false;`

2021-10-27 15:51 UTC, confluence approved these changes

2021-10-27 18:50 UTC, jolopezl requested changes
I have a few comments. A couple of minor comments, and another more general across the changes regarding the use of `fs::exists`. Is the purpose of using `fs::exists(p, ec)` just using the overload of `fs::exists` that doesn't throw an exception?

2021-10-27 18:50 UTC, jolopezl commented on src/Frame.cc
> +    if (fs::exists(output_filename, error_code) && !error_code) {
Why do you check twice the result of `fs::exists`? The return value is `true` if the path exists and `false` if it does not. You can use `error_code` just in case something goes wrong. I suggest you change this line and use `error_code` afterward only to investigate what went wrong (a system-dependent error code). Do you really need it?

2021-10-27 18:50 UTC, jolopezl commented on src/SessionManager/ProgramSettings.cc
> +    no_system_config = result.count("no_system_config") != 0;
I wouldn't say I like this change. IMO, The former version is more explicit (not that I originally wrote it...), while the second version is less friendly. Also, on the other hand, you can do:
```
    no_user_config = result.count("no_user_config");
    no_system_config = result.count("no_system_config");
```
With this, the code looks less complicated. It also avoids any comparison, which is a plus. 

In the end, all versions will look the same when compiled (thank you compiler), but reading is quite important for the future.

2021-10-27 18:50 UTC, jolopezl commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
>          return json::parse(json_string);
Not entirely related to this pull request, but what's the purpose of the try-catch construct here if the exception isn't handled? Maybe something is missing like:
```
catch (exception e) {
        spdlog::warn(e.what());
        return {};
    }
```

2021-10-27 18:50 UTC, jolopezl commented on src/Frame.cc
> +    if (fs::exists(output_filename, error_code) && !error_code) {
This comment propagates to the rest of the changes, for both cases:
```
fs::exists(p, ec) && !ec
```
and
```
!fs::exists(p, ec) || ec
```

2021-10-27 18:54 UTC, jolopezl commented on src/Frame.cc
> +    if (fs::exists(output_filename, error_code) && !error_code) {
I suggest adding across the changes something like:
```
if (fs::exists(p, ec) {
    // ...
} else {
    spdlog::debug(fmt::format("failed with error code {}", ec));
}
```
or just ignore the error_code result.

2021-10-28 07:57 UTC, veggiesaurus commented on src/Frame.cc
> +    if (fs::exists(output_filename, error_code) && !error_code) {
I think we can just ignore the error code, you're right. It's really just there so that we can use the `no_except` version of the call

2021-10-28 08:05 UTC, veggiesaurus commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
>          return json::parse(json_string);
good point, this was inconsistent. Fixed

2021-10-28 10:11 UTC, jolopezl requested changes

2021-10-28 10:11 UTC, jolopezl commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
> +    if (accepts_gzip && fs::exists(gzip_path, error_code) && fs::is_regular_file(gzip_path)) {
Here `fs::is_regular_file(gzip_path)` should also be `fs::is_regular_file(gzip_path, error_code)` so that it doesn't throw. It has almost the same signatures as `fs::status` (https://en.cppreference.com/w/cpp/filesystem/is_regular_file).

2021-10-28 10:11 UTC, jolopezl commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
> +    if (fs::exists(path, error_code) && fs::is_regular_file(path)) {
Idem for `fs::is_regular_file`, and in more places in the rest of the changes.

2021-10-28 10:11 UTC, jolopezl commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
> +    if (!fs::exists(folder, error_code) || !fs::is_directory(folder)) {
Idem for `fs:: is_directory` (https://en.cppreference.com/w/cpp/filesystem/is_directory),  and in more places in the rest of the changes.

2021-10-28 10:11 UTC, jolopezl commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
>          return json::parse(json_string);
Great!, but now I got a bit confused with this try-catch construct. 
Right now, `fs::exists` and `json::parse` can throw. Shouldn't we try to catch both exceptions? So, I think the previous position of `fs::exists` was fine, and you can use the `noexcept` version of it, but the try-catch construct should be changed a little bit to catch the json parse error: ` catch(json::parse_error& e) spdlog::warn(e.what());`

2021-10-28 10:11 UTC, jolopezl commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
>                  string filename = p.path().filename().string();
Following up on my last thought. Two lines below here, the try-catch construct will need to catch two exceptions. Maybe it's better to change `fs::is_regular_file(p)` to `fs::is_regular_file(p, error_code)` and just try to catch the possible exception from `json::parse`. What do you think?

2021-10-29 09:55 UTC, confluence commented
I agree that we should be consistent about either using the functions that throw or the functions that do not.

2021-10-29 11:04 UTC, veggiesaurus commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
> +    if (accepts_gzip && fs::exists(gzip_path, error_code) && fs::is_regular_file(gzip_path)) {
good point. Have done the same for `is_directory`

2021-10-29 11:05 UTC, veggiesaurus commented on src/SimpleFrontendServer/SimpleFrontendServer.cc
>                  string filename = p.path().filename().string();
have fixed this too :+1:

2021-10-29 11:06 UTC, veggiesaurus commented
> I agree that we should be consistent about either using the functions that throw or the functions that do not.

I have changed them all, except for one: `SimpleFrontendServer::ClearObjectFromString` has calls in a try-catch and we actually _want_ to get hold of the exception information in this case, so I've left it is.

2021-10-29 11:12 UTC, confluence approved these changes

2021-10-29 13:34 UTC, jolopezl approved these changes
Thanks for addressing the comments!. Looks great.

2021-10-29 13:38 UTC, merged